### ISSUE TITLE
Add ACSS support

### ISSUE THREAD

**Issue by chinchang** [chinchang/web-maker#100]
Using atomizer to create CSS from HTML: https://github.com/acss-io/atomizer

CC @pankajparashar @jitendravyas

**Comment by pankajparashar** [comment]
Atomizer is actually an npm module. I had created a web editor for Atomic CSS, a few years back.
https://github.com/pankajparashar/atomizer-web

This might be something you could look at. Although the code is shambolic!

And there is also a Chrome extension, if it fits here, 
https://github.com/acss-io/codepen-atomizer.crx

**Comment by chinchang** [comment]
@pankajparashar Your `atomizer-web.js` is just browser bundled form of the atomizer npm module right?

**Comment by chinchang** [comment]
Live in 2.5.0 (without configuration options). Thanks @pankajparashar for your Atomizer Web :)

**Comment by jitendravyas** [comment]
Cool. I just checked and it's working.
