### ISSUE TITLE
Have web maker work offline as a website also

### ISSUE THREAD

**Issue by chinchang** [chinchang/web-maker#101]
Web Maker can work offline as a website too using service worker. This will make it available as it is but without installing an extra chrome extension.

**Challenges:**

- [ ] How will Chrome synced settings be shared?
- [x] Features only possible with Chrome extension APIs?
- [x] What about the saved creations? How will they be shared?
- [x] webkitRequestFilesystem API is Chrome only! (required to render preview)

**Comment by lishengzxc** [comment]
+1

**Comment by chinchang** [comment]
Its live in 3.0 -> https://webmakerapp.com/app/ 🔥
