### ISSUE TITLE
Incorrect indentation

### ISSUE THREAD

**Issue by jkantner** [chinchang/web-maker#104]
I found an indentation bug where tabs go farther than I have set them. I’m using tabs with an indentation size of 4, and every new line I enter is indented 10 times more instead of starting at the same level. Here’s what I’m talking about:

![licecap_gif](https://cloud.githubusercontent.com/assets/16387543/24830230/7efd7d98-1c4f-11e7-9ff2-f87c86b44bd3.gif)

I have applied the same settings in CodePen, and this is how they should work:

![licecap_gif2](https://cloud.githubusercontent.com/assets/16387543/24830275/87731e78-1c50-11e7-8782-6591ca42b787.gif)

**Comment by chinchang** [comment]
@jkantner Is it a persistent issue or happens sometimes? I tried with tab with size 4 and cannot seem to reproduce the same. Would appreciate some more help here :)

**Comment by jkantner** [comment]
@chinchang It’s persistent. To reproduce it yourself, try to create a function containing an anonymous function like this (or can be self-invoked):
```
function doStuff() {
	let anonFn = function(){
				
	};
}
```
If you press Enter after typing `function(){`, you’ll get the over-indent on the next line. I believe this only happens while typing anonymous functions. Indents are still fine while creating variables for things other than anonymous functions.

**Comment by chinchang** [comment]
This is fixed in v2.5.0. Thanks for reporting @jkantner 👍
