### ISSUE TITLE
How about using Ace instead of codemirror?

### ISSUE THREAD

**Issue by meain** [chinchang/web-maker#105]
In my opinion [Ace](https://ace.c9.io/) would be better choice to Codemirror.

https://ace.c9.io/build/kitchen-sink.html

**Comment by chinchang** [comment]
@meain Any specific reasons why you recommend Ace? Or any issues you have seen with CodeMirror in current version?

**Comment by meain** [comment]
Don't really have any issues with Codemirror, but seems like Ace is bit more mature and has a cleaner api than Codemirror. I just thought I would get your opinion on using Ace.
