### ISSUE TITLE
Font Awesome Icon Don't Show

### ISSUE THREAD

**Issue by ronaldroe** [chinchang/web-maker#106]
I added Font Awesome using the library function. I used the version that comes up when you start typing the name, but icons show as empty blocks.

**Comment by chinchang** [comment]
Can you confirm if you have `https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css` in the Add Library CSS textarea?

I tried with the following HTML:
`<i class="fa fa-camera-retro"></i> fa-camera-retro`

and it seems to work.

Will appreciate any more information on this.

**Comment by ronaldroe** [comment]
That is the same URL in my Add Library CSS textarea, and the same HTML. I'm getting just an empty rectangle.

**Comment by ronaldroe** [comment]
I got it fixed. There was a font declaration that, even though it was overridden, was causing the issue.
