### ISSUE TITLE
Web Maker stop working, blank page

### ISSUE THREAD

**Issue by fmigliorato** [chinchang/web-maker#114]
As the title say, I get a blank page on every page/edit I make
My Chrome version is _58.0.3029.110 (64-bit)_. Thanks in advance for any support

**Comment by chinchang** [comment]
@fmigliorato I faced the same issue few days back and was debugging it. And all of a sudden it started working again. Can you please try restarting your Chrome and see if it starts working again. Meanwhile I am trying to debug & fix a probable cause of this.
Let me know.

**Comment by fmigliorato** [comment]
@chinchang Thanks for the quick reply, I restarted Chrome but unfortunately nothing happened :(

**Comment by fmigliorato** [comment]
Restarting the pc fixed it. Thank You 👍
