### ISSUE TITLE
Include externl css or js.

### ISSUE THREAD

**Issue by aman-roy** [chinchang/web-maker#12]
I can't include my bootstrap or Jquery files for testing. Can it be solved?

**Comment by chinchang** [comment]
How exactly are you including your jquery files?

**Comment by aman-roy** [comment]
something like this --> <script src="./js/jquery.min.js"></script>

**Comment by chinchang** [comment]
@aman-roy Your last comment was incomplete I suppose.

**Comment by aman-roy** [comment]
Ya...sorry....
something like this  --->   <script src="./js/typed.js"></script>

**Comment by aman-roy** [comment]
Ya sorry...
It's something like this -> < script src = " ./js/typed.js " > < / script >

**Comment by chinchang** [comment]
`./js/typed.js` means a JavaScript file in the current directory/folder. In web-maker their is no directory or files. Its just your html, css and JS code. For any external library that you want load, give a full path of that file. Eg. To load jQuery: `http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.js`
