### ISSUE TITLE
Add framer.js to the externally loadable libraries

### ISSUE THREAD

**Issue by lobau** [chinchang/web-maker#128]
Framer.js would be wonderful to do quick prototypes in Web Maker.
Loading the latest from https://builds.framerjs.com/ would be great.

**Comment by chinchang** [comment]
Since fetching the latest framer.js library would be a little tricky, do you think the current build url should be added to the list of common libraries?
Remember, you can use framer.js still by putting in the URL of framer.js library in the external JS textarea.

**Comment by lobau** [comment]
Adding the build url to the list of common libraries would definitely solve the issue. Thanks!

**Comment by chinchang** [comment]
@lobau Now you can add framer.js url from their build pages and create prototypes inside Web Maker.
For example, click on 'Add library'. Put in the framer.js url -> `https://builds.framerjs.com/580846c/framer.js` and paste the following JS in the editor:

```
// Welcome to Framer

// This is just demo code. Feel free to delete it all.

imageLayer = new Layer({x:0, y:0, width:128, height:128, background: '#f00' })
imageLayer.center()

// Define a set of states with names (the original state is 'default')
imageLayer.states = {
	second: {y:100, scale:0.6, rotationZ:100},
	third:  {y:300, scale:1.3},
	fourth:	{y:200, scale:0.9, rotationZ:200}
}

// Set the default animation options
imageLayer.animationOptions = {
	curve: "spring(500,12,0)"
}

// On a click, go to the next state
imageLayer.on(Events.Click, function() {
	imageLayer.stateCycle()
})
```
