### ISSUE TITLE
Missing crucial default library

### ISSUE THREAD

**Issue by gavinggordon** [chinchang/web-maker#129]
I just noticed that the default library is missing a crucial javascript library.
 
As one would expect, the default library does provide _Bootstrap's stylesheet (css) CDN_:
**https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css**

Oddly, however, I just noticed that _Bootstrap's javascript (js) CDN_ is __NOT__ provided:
**https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js**

**Comment by chinchang** [comment]
This is getting fixed in coming version (2.7).

**Comment by chinchang** [comment]
fixed in 2.7
