### ISSUE TITLE
how can we switch to our own font?

### ISSUE THREAD

**Issue by diomed** [chinchang/web-maker#136]
I have premium font installed on PC. 
How could I switcht to display it instead of other free fonts?

**Comment by chinchang** [comment]
No way as of now, but I guess we can have a custom field in fonts section where anyone can specify an installed font name. Will take this up.

**Comment by chinchang** [comment]
For reference, the `getFontList` API can be used -> https://developer.chrome.com/extensions/fontSettings#method-getFontList

**Comment by chinchang** [comment]
This is live in 2.8.0. Thanks for suggesting :)
