### ISSUE TITLE
no menu items are working.

### ISSUE THREAD

**Issue by ngangchill** [chinchang/web-maker#147]
when i click on menu such as setting /  save /open / new etc. nthing happen. console window does not expand.    in chrome console it shows:

![screenshot20170618041439](https://user-images.githubusercontent.com/4242225/27256629-d0344ace-53dc-11e7-8388-96486df9eb3e.png)

![screenshot20170618041515](https://user-images.githubusercontent.com/4242225/27256631-de4da358-53dc-11e7-8208-59e210852102.png)

**Comment by chinchang** [comment]
@ngangchill Can you please let me know you Chrome browser version. BTW, I checked it on latest stable (v59) and it works fine.
Let me know.

**Comment by ngangchill** [comment]
@chinchang 

![capture](https://user-images.githubusercontent.com/4242225/27258015-e27151fe-540f-11e7-89fc-0f14eb7d1f52.PNG)

**Comment by chinchang** [comment]
I see. I didn't knew Chrome extension could be run on UC Browser! I'll fix this :)

**Comment by ngangchill** [comment]
thanx for quick replay... :+1:

**Comment by ngangchill** [comment]
Works as usual in uc browser. Thnx for the fix
