### ISSUE TITLE
Add Foundation JS to Popular Libraries Selection

### ISSUE THREAD

**Issue by dfeeney-mt** [chinchang/web-maker#148]
I use Foundation for everything, and I love that the Foundation CSS is already added. It would be great if the Foundation JS was added to the Popular Libraries selection so I don't have to go searching for the URL on a CDN separately. 

Thanks

**Comment by chinchang** [comment]
Sure. Will add that in coming release.

**Comment by chinchang** [comment]
This is live in 2.7.2. Thanks for bringing this up 😄

**Comment by dfeeney-mt** [comment]
Thank you very much!
