### ISSUE TITLE
webkitStorageInfo error in console

### ISSUE THREAD

**Issue by chinchang** [chinchang/web-maker#158]
[Deprecation] 'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.

Reported by @diomed

**Comment by chinchang** [comment]
@diomed I tried some code on Canary Version 61.0.3149.0 (Official Build) canary (64-bit). But didn't encounter the reported error in developer console.
Can you please give some more details where & how exactly did you see this error?

**Comment by diomed** [comment]
I was trying out this:
https://play.celljs.org/items/1ZrfV1/edit

**Comment by chinchang** [comment]
Well that is celljs.org's issue then :) I am not sure why you found it related Web Maker?

**Comment by diomed** [comment]
![.](https://m.popkey.co/cc844c/brLbK.gif)

I'm sorry. I'm n00b. 👶  U can close an issue then.

**Comment by chinchang** [comment]
No problem :)
