### ISSUE TITLE
When "save as HTML file", the generated HTML need a utf-8 encode meta tag.

### ISSUE THREAD

**Issue by awguo** [chinchang/web-maker#173]
This is a great tool.

But when exporting as HTML file, the HTML should include a UTF-8 encoding meta tag as:

`<meta http-equiv=Content-Type content="text/html; charset=utf-8">`

Otherwise some Chinese characters are not displaying correctly.

**Comment by chinchang** [comment]
Thanks @awguo 
Sure, I'll fix that.

**Comment by chinchang** [comment]
Added `<meta charset="UTF-8" />` in v2.8.1
