### ISSUE TITLE
Geolocation not working

### ISSUE THREAD

**Issue by MikePolinske** [chinchang/web-maker#177]
It seems that geolocation doesn't work in Web Maker.  I tried the following HTML and none of the variables are filled in on the preview.

<!doctype html>
<html>
    <head>
        <title>Geolocation</title>
    </head>
    <body>
        <p>Latitude: <span id="latSpan"></span></p>
        <p>Longitude: <span id="longSpan"></span></p>
        <p>More or less: <span id="accSpan"></span> meters</p>
        <script>
            var options = {
                enableHighAccuracy: true,
                timeout: Infinity,
                maximumAge: 0
            };
            navigator.geolocation.getCurrentPosition(success, fail, options);

            function success(position)
            {
                var lat = position.coords.latitude;
                var long = position.coords.longitude;
                var acc = position.coords.accuracy;
                document.getElementById('latSpan').innerHTML = lat;
                document.getElementById('longSpan').innerHTML = long;
                document.getElementById('accSpan').innerHTML = acc;
            }
            function fail(error)
            {
                alert("Error: " + error.code + " " + error.message);
            }
        </script>
    </body>
</html>

**Comment by chinchang** [comment]
@MikePolinske You cannot use script tags in Web Maker. You should put your script in the JS panel and HTML in the HTML panel. Then it will work.

**Comment by MikePolinske** [comment]
Thank you.
Mike Polinske
Milwaukee, WI
Follow me on Twitter <http://twitter.com/mikepolinske>. I'm also on Facebook <http://www.facebook.com/mikepolinske>. Check out my blog! <https://blog.mikepolinske.info/>
Who is Jesus? Find out at What about Jesus? <http://www.whataboutjesus.com/>
