### ISSUE TITLE
feature request : Full screen editing

### ISSUE THREAD

**Issue by khaled-nuur** [chinchang/web-maker#183]
### Hi!:hand::hand:
I will love not to confuse with the opened browser tabs:bowtie:.
and I can say confidently that there is no popular/great code editor that doesn't have full screen mode(tested ~5 editors:sparkles::sparkles:).
just add full screen library and add a button next to settings.
:heart:that is all:heart:
:heart:looking forward:heart:

**Comment by chinchang** [comment]
Sure, great suggestion. Thanks!

**Comment by khaled-nuur** [comment]
closed here✨✨✨✨

**Comment by khaled-nuur** [comment]
closed here✨✨✨✨

**Comment by chinchang** [comment]
@khaled-nuur Why closed this?

**Comment by khaled-nuur** [comment]
@chinchang 

![because of this](https://user-images.githubusercontent.com/28248852/30357670-91f00efa-9848-11e7-8a68-b582909344a4.PNG) 
above was the answer to my question
we are waiting for **2.9.0**, with this feature.
```js
    smaller issues === good development team;
    more closed issues === good updates;
    more issues === bad/no team behind the app;
````
