### ISSUE TITLE
webmakerapp.com should display compatibity info on other browsers

### ISSUE THREAD

**Issue by silverjoshi** [chinchang/web-maker#185]
The webmakerapp.com is confusing for Firefox users. On chrome browser, install button appears but no compatibility info is displayed on Firefox, so the firefox users who just got to know about webappmaker and want to try it will be confused due to lack of instructions regarding how to install&use it.
Just a single line message indicating that webmakerapp is only available on Chrome would be enough to resolve this issue

**Comment by chinchang** [comment]
Agree. Will add this asap. Thanks for reporting.

**Comment by chinchang** [comment]
Done.
