### ISSUE TITLE
Add duplicate cursor CMD/CTRL+D shotcut like in Sublime Text

### ISSUE THREAD

**Issue by thiemeljiri** [chinchang/web-maker#196]
Hey,

I already mentioned how great this extensio is, but I have to do it again!

I have a feature request to make the editor more Sublime text like. Please add a shortcut CMD+D (CTRL+D) to duplicate the cursor. This feature is called "Quick Add Next" In Sublime Text.

Thanks!

**Comment by chinchang** [comment]
This is live in v2.9.1. Update now :) Thanks for suggesting @thiemeljiri and @BasitAli for implementing it!
