### ISSUE TITLE
demo in screenshot breaks with opacity.

### ISSUE THREAD

**Issue by trusktr** [chinchang/web-maker#202]
Hello, when I try to apply opacity to the cube from the demo screenshot, it becomes no longer a cube, just a flat square. Does it work for you if you apply opacity to the `.cube`?

**Comment by chinchang** [comment]
Would need some more context...what screenshot and cube are we talking about here?

**Comment by trusktr** [comment]
The [screenshot in the README](https://github.com/chinchang/web-maker#install-extension). Does it still work for you if you apply `opacity:0.5` to the `.cube` style?

**Comment by chinchang** [comment]
Oh, I see. Are you implementing the same code from the screenshot? If so, the CSS there isn't complete, there is more below the scroll. If you want the complete code, you can get it here -> https://codepen.io/chinchang/pen/JrWWBr

**Comment by trusktr** [comment]
Cool, thanks, this is what I meant: look at how it breaks when I apply opacity to the `.cube` (first line of CSS): https://codepen.io/trusktr/pen/MEORbE

**Comment by chinchang** [comment]
Seems like a bug in how `opacity` is handled with `transform-style` by browser. I think this issue can be closed as this isn't a Web Maker bug? :)

**Comment by trusktr** [comment]
Actually, it's not a bug. This is how opacity is supposed to work now according to the new CSS transform spec. Here's an issue on Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=646993

This is bad, isn't it! The browsers have agreed to break 3D apps by following specs. Was just making this issue to point that out and raise awareness of this horrible change.

**Comment by chinchang** [comment]
@trusktr Agree with your point. Though closing this as the bug belongs to Chromium.
