### ISSUE TITLE
Requesting help for an open source project

### ISSUE THREAD

**Issue by adinarayaanraghu95** [chinchang/web-maker#203]
Hello there. 
Tried finding your contact email ID , but unfortunately I couldn't find it anywhere and which is why I am sorry , I am writing here . 

Kindly send a mail at adinarayanaraghu95@gmail.com

I could explain you further about the project so you could see if you could help us. 

Alternativel you can also text at 8660626844 .

**Comment by chinchang** [comment]
Mailed you.
