### ISSUE TITLE
Find Next/ Find Previous  (Key Mapping): Enhancement Request

### ISSUE THREAD

**Issue by jimmck** [chinchang/web-maker#205]
Hi,
Find is is good to highlight items. But the ability to move back and forth between occurrences is really important. Otherwise I have to cut and paste the code into Sublime.

So CMD+N to forward / Shift+CMD+N to backwards.

And the ability to map these editor keys so we don't get conflicts with chrome.

But enjoying each New Release, Thank You!

Jim

**Comment by chinchang** [comment]
v2.9.5 release just now which has a list to see all available shortcuts in the app. What you require is also present: Find Next - `Ctrl/⌘ + G` Find Previous - `Ctrl/⌘ + Shift +  G`
