### ISSUE TITLE
Where is the saved files?

### ISSUE THREAD

**Issue by sreenadhp** [chinchang/web-maker#208]
I am a new user and I am unable to find where are the files saved when I click "save" button on the  top left.

**Comment by jimmck** [comment]
Save updates the plugin's project cache with updated code changes. You can export all of the saved projects to a JSON file using the export button in the Open menu. You can also generate an HTML file from the bottom menu, the Arrow Icon.

**Comment by sreenadhp** [comment]
I would like to have the whole project cache in my dropbox folder, so all my data is backed up. I find web maker as a nice tool to experiment with.

**Comment by chinchang** [comment]
+1 to what @jimmck said.

@sreenadhp You'll be able to backup all your work wherever you want once #200 is implemented.

**Comment by chinchang** [comment]
@sreenadhp Fromversion 2.9.3 (already live) you can now tell the location where all your creations are exported. So select your dropbox folder and all your creations will be backed up :)
