### ISSUE TITLE
"Take a screenshot of preview" cuts off the image on Retina display.

### ISSUE THREAD

**Issue by MrCoder** [chinchang/web-maker#209]
The onImgLoad method does not take devicePixelRatio into consideration and is producing a wrong image with main content cut off.

This can be fixed with this solution found at SO: https://stackoverflow.com/questions/30537138/rendering-html-to-canvas-on-retina-displays .

![web-maker-screenshot-2017-10-1-16-47-6](https://user-images.githubusercontent.com/169417/31052389-c33636f8-a6ce-11e7-9d97-6bed5140f7a7.png)

**Comment by chinchang** [comment]
fixed in 2.9.3. Thanks @AshBardhan
