### ISSUE TITLE
UI Issue when in console window

### ISSUE THREAD

**Issue by vikrantnegi** [chinchang/web-maker#211]
The Editors gutters space with line numbers overlaps the console window when the console is pulled over the editors. 

Here is the screenshot for the same: 
<img width="862" alt="screen shot 2017-10-03 at 13 11 53" src="https://user-images.githubusercontent.com/3294287/31114712-ff33adc4-a83c-11e7-81f2-62ca6a6e46d7.png">

Thanks.

**Comment by redstone2010** [comment]
#Hacktoberfest

**Comment by chinchang** [comment]
live in 2.9.4
