### ISSUE TITLE
Option to remove the checkbox to toggle boolean values

### ISSUE THREAD

**Issue by GianCastle** [chinchang/web-maker#214]
### Description

When a boolean value is focus on the editor, a checkbox appear on top of this value. 
_Screenshot provided_

![image](https://user-images.githubusercontent.com/6842883/31390673-81626ff0-ada2-11e7-91ca-d7b690532f91.png)

As a user, i want to remove this checkbox on the settings section.

**Comment by willamesoares** [comment]
I can take a look at this :slightly_smiling_face:

**Comment by gauravmuk** [comment]
There are two approaches for this:

1. We will need an option inside Inlet.js to toggle the feature being offered by it. I could not find an "off" flag. If we go by this approach, it will require modifying the inlet.js file and all we would require is sending a flag.
2. This approach is a bit dirty. We will need to reload the entire web maker window to remove the processing being done by Inlet.

Let me know which one sounds better, i will be happy to fix this. cc @chinchang

**Comment by chinchang** [comment]
I added Inlet.js as an experiment to see if it can really help in quick value tweaking. But IMO, its user experience is more intrusive than helpful (clear from PR such as this & #115). For the same reason, Inlet.js' slider that showed on clicking a number was commented off in the inlet.js file sometime back. The only thing that is really useful is the color picker that shows on clicking a color.

So I would say we remove Inlet.js altogether and if possible just integrate a nice color picker in Codemirror. What say?

**Comment by chinchang** [comment]
This has been removed in 2.6.1. Closing.
