### ISSUE TITLE
Omnibar text no longer selected

### ISSUE THREAD

**Issue by Kachilero** [chinchang/web-maker#218]
I recently updated to MAC High Sierra and this may very well be a MAC and/or Chrome issue.
Previously when I would open a new tab, the text in the omnibar on Chrome would all be selected so that I could just start typing a URL directly.
After updating, the cursor appears in the omnibar, but at the start of the URL, so that if I start typing, it gets prepended to the URL instead of replacing it.

**Comment by chinchang** [comment]
Noticed the same thing in latest versions of Chrome and as you mentioned, it seems to be some change in Chrome.
Just so you know, if this starts interfering with your input too much, you can set in Settings - not to show Web Maker in every tab tab.

**Comment by chinchang** [comment]
Seems like its fixed in Chrome 62. Can someone confirm?

**Comment by Kachilero** [comment]
I just updated to Chrome 62 and the issue does seem to be resolved.

**Comment by chinchang** [comment]
Great! Closing.
