### ISSUE TITLE
Is <script> not supported?

### ISSUE THREAD

**Issue by sreenadhp** [chinchang/web-maker#220]
In the HTML pane, I pasted the below code and no response but it did work in codepen.io & jsbin.
`  <script>
    document.write("hello");
  </script>`

I just curious to know why? Is it a bug or by design? I was actually comparing the features of with codepen & jsbin.

**Comment by chinchang** [comment]
This restriction comes from being a Chrome extension. Inline scripts are a source of security attacks and hence is blocked by Chrome extension environment.
