### ISSUE TITLE
[bug] Detached Preview Mode: possible script double execution 

### ISSUE THREAD

**Issue by nukadelic** [chinchang/web-maker#223]
When running the script in detached preview mode im getting double outputs in the WebMaker-Console. Including on timer events. were Chrome-dev tools console displaying only one instance output. 

Chrome console:

```md
>> FIRST LINE <<                       screenlog.js:159
1. On time interval                    screenlog.js:159
2. On time interval                    screenlog.js:159
3. On time interval                    screenlog.js:159
4. On time interval                    screenlog.js:159
5. On time interval                    screenlog.js:159

```
WebMaker console:
```md
>> FIRST LINE << 
1. On time interval 
>> FIRST LINE << 
1. On time interval 
2. On time interval 
2. On time interval 
3. On time interval 
3. On time interval 
```

**Comment by chinchang** [comment]
Ahh I see. That is happening because the main preview iframe still exists (hidden) even when you are in detached mode :) Will need to stop it from sending logs in detached mode.
