### ISSUE TITLE
[fix]? - Uncaught TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by nukadelic** [chinchang/web-maker#224]
Whenever i try and log a circular object, WebMaker console fails to output it and makes the variable impossible to read in chrome dev-tools. 

I found a temporary fix for the problem, instead of console.log, now I'm using the `log` function:
```js
function log(object)
{
  //https://stackoverflow.com/a/14962496/2496170 (minified version)
  function isCyclic(r){function n(r){if(r&&"object"==typeof r){
  if(-1!==i.indexOf(r))return!0;i.push(r);for(var t in r)if(
  r.hasOwnProperty(t)&&n(r[t]))return!0}return!1}var i=[];return n(r)}
  
  var output = isCyclic(object)?object.toString():object;
  console.log( output );
}
```

i like your tool, it works smoothly on my machine compared to CodePen
... can we have an option in settings to temporary disable WebMaker console ?

**Comment by chinchang** [comment]
Its now possible to see the log in the browser's console at least. Inside Web Maker it shows in some mysterious way :)
