### ISSUE TITLE
Question : desktop app 

### ISSUE THREAD

**Issue by akashnimare** [chinchang/web-maker#229]
I was thinking to build a desktop app using Electron on top of web-maker. That way people can use it as a code editor app on Linux/Windows as well. What do you think on this?

**Comment by chinchang** [comment]
Hi @akashnimare This discussion is already going on a separate issue -> #77
Though, my opinion is to more focus and get out an offline working web app rather than firefox or electron. Would love it get some help on that.
Closing this as duplicate.
