### ISSUE TITLE
JavaScript function calling is not working from HTML

### ISSUE THREAD

**Issue by mailmonir** [chinchang/web-maker#232]
I tried to call javascript function from html button using click event but it's not calling the function

**Comment by wordandahalf** [comment]
+1
I experience this as well.

**Comment by chinchang** [comment]
Due to Chrome security restrictions, you cannot have inline JavaScipt. `onclick` in HTML is inline JavaScript, and so it doesn't work. Solution is to have all JavaScript in JavaScript code panel and attach click event with say, `addEventListener` function.
