### ISSUE TITLE
Add prettier as an option for formatting code

### ISSUE THREAD

**Issue by chinchang** [chinchang/web-maker#234]
Right now Shift+tab auto formats any selected code. This is codemirror's native formatting. But Web Maker could give an option to format code with prettier too. That might be helpful to certain developers.
https://github.com/prettier/prettier

**Comment by skwurw** [comment]
Would be nice if this was an option to enable/disable. I usually use shift+tab to unindent selected code I have that isn't lined up correctly.

**Comment by chinchang** [comment]
Valid point. Will take care of that.
