### ISSUE TITLE
Close buttons on imported modals refreshes the page

### ISSUE THREAD

**Issue by ClassicOldSong** [chinchang/web-maker#239]
https://github.com/chinchang/web-maker/blob/949008f9ce4a37d834352dcfa4f045f27339b456/src/changelog.html#L1
https://github.com/chinchang/web-maker/blob/949008f9ce4a37d834352dcfa4f045f27339b456/src/keyboard-shortcuts.html#L1

These two click bindings never worked. It just refreshes the page.

**Comment by chinchang** [comment]
Ahh, right. The `d-click` directives don't compile anymore. Thanks for reporting. Will fix.
