### ISSUE TITLE
ReferenceError: d3 is not defined

### ISSUE THREAD

**Issue by gitjps** [chinchang/web-maker#254]
please see 
https://stackoverflow.com/questions/48529027/referenceerror-d3-is-not-defined-using-web-maker

also, do you have a stackoverflow tag?

**Comment by chinchang** [comment]
Answered on Stackoverflow. Added the "web-maker" tag as well. Copying the answer here also.

The script content will move to the JS pane. But the external scripts need to be loaded through the "Add library" button. In the "Add library" box, simply select D3 from the list of popular libraries.

![webmaker-d3-error](https://user-images.githubusercontent.com/379918/35588906-1ae75770-0628-11e8-8041-e97844a40eca.png)

**Comment by gitjps** [comment]
thx for the prompt response
