### ISSUE TITLE
Save as HTML issue

### ISSUE THREAD

**Issue by RamGRam** [chinchang/web-maker#274]
Save as HTML is having issue, and I am not able to get an html file as output, but a filename.file of size 2kb is saved!

**Comment by RamGRam** [comment]
Hey when I manually apply .html extension and save it, its generating the html file.  I see it is not saving as .html by default.

**Comment by chinchang** [comment]
Publish in progress. Will update when its live.

**Comment by chinchang** [comment]
fixed and live in v3.0.3. Thanks for reporting @RamGRam :)
