### ISSUE TITLE
React development appears not to work

### ISSUE THREAD

**Issue by ljh65536** [chinchang/web-maker#277]
**Steps to reproduce:**

1. In Settings, select the ES6 (Babel) preprocessor
2. In Add Library, include the React and ReactDOM packages that come with web-maker.  Alternatively, include //cdnjs.cloudflare.com/ajax/libs/react/0.13.0/react.min.js
3. Put this in for HTML:
`<div id="root">not replaced yet</div>`
4. Put this in for js:
`class App extends React.Component {
  render() {
    return(<p>Stuff replacing</p>);
  }
}
React.render(<App />, document.getElementById('root'));`

**Results**:
You get a bunch of `SyntaxError: Unexpected token < `

**Expected**: 
For the app to compile

**Notes**:
I expect this is a problem with the babel ES6 framework not working, since it's not liking the < mark, which implies to me that it's reading it as straight js.

**Comment by chinchang** [comment]
Hi @ljh65536 
Try this in you JS:

```
class App extends React.Component { render() { return(<p>Stuff replacing</p>); } } 
ReactDOM.render(<App />, document.getElementById('root'));
```

`render` function is available on ReactDOM

**Comment by chinchang** [comment]
Please reopen if my last comment doesn't help.
