### ISSUE TITLE
Aspect ratio preview suggestion

### ISSUE THREAD

**Issue by JipFr** [chinchang/web-maker#278]
I'd like to implement a feature in settings that allows you to override the default aspect ratio (which, obviously, is defined by the width of the browser minus the editing fields.)

This could be useful for making sites responsive, seeing how they look on mobile phones or tablets, etc.

**Comment by chinchang** [comment]
I assume this feature pertains more to the height of the preview window, correct? Because the preview width is already changeable through dragging.

**Comment by JipFr** [comment]
Yes, that’s what I had in mind. It’s barely possible to get an exact AR by simply redragging the window

**Comment by chinchang** [comment]
Interesting! Let's take forward 👍

**Comment by JipFr** [comment]
Oops, didn't mean to do that.

**Comment by JipFr** [comment]
I think we can safely say this can be closed
