### ISSUE TITLE
Javascript console UI Issue

### ISSUE THREAD

**Issue by RamGRam** [chinchang/web-maker#280]
I am using the chrome extension, and there is a ui issue in the JS console area, where the console input is half displayed!

**Comment by chinchang** [comment]
Any screenshots please?

Also, does it always show wrong or there are some steps to reproduce?

**Comment by RamGRam** [comment]
Sorry for my late reply, here is the screenshot

![jsconsole](https://user-images.githubusercontent.com/22612511/38484266-a3a3ba12-3bf3-11e8-8b62-d8e0d64442ed.png)

**Comment by chinchang** [comment]
Hi @RamGRam 
Can you please help me verify this issue in latest release (v3.3.1) on your end, still present?

**Comment by chinchang** [comment]
fixed in #327

**Comment by chinchang** [comment]
Hi @RamGRam 
This should be fixed in v3.4.2. Please let me know here if it's not.
