### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by joseluisq** [chinchang/web-maker#29]
![image](https://cloud.githubusercontent.com/assets/1700322/21653743/e7a9c220-d2b2-11e6-8e82-5641d9d7d141.png)
http://codepen.io/chriscoyier/pen/XbjXXW

**Comment by chinchang** [comment]
Sure! This will be useful addition.

**Comment by chinchang** [comment]
Added in 2.1.0

**Comment by joseluisq** [comment]
Great !

![image](https://cloud.githubusercontent.com/assets/1700322/22070814/9ec352c4-dd9d-11e6-8018-5ef609958e99.png)

**Comment by joseluisq** [comment]
Like a enhancement, it would be great to add syntax checking.

![image](https://cloud.githubusercontent.com/assets/1700322/22071167/9e6daa58-dd9e-11e6-9e99-8baa787185fb.png)
