### ISSUE TITLE
Save as HTML and RUN issues

### ISSUE THREAD

**Issue by FluffyDoggoOfficial** [chinchang/web-maker#290]
After turning on **auto-preview**, then turning it off, the _RUN_ function breaks; It no longer works. Also, I have been having problems saving my projects as html files in the chrome extension. However, the online webmaker works fine, but I still have problems with the RUN function. Can you please fix? I'd love the get back to working on my projects. Webmaker has always been reliable, and this saddens me that I can't get working on coding. It would make my day if these bugs got fixed. Also, I have a video [HERE](https://www.useloom.com/share/5faa87d961e44676985e3bc4091a78ee) that shows the RUN bug. Thanks.

-Fluffy Doggo

**Comment by chinchang** [comment]
Hi @FluffyDoggoOfficial Can you please mention the version of Web Maker you are using as Chrome extension?

**Comment by chinchang** [comment]
The "run" bug is fixed and will be live in version 3.1.1. Though I could not understand you concern with saving html file functionality. Please open a separate issue for the same explaining the problem.
Also, I'll soon start working on tests to make the releases more reliable.
Thanks for reporting :)

**Comment by chinchang** [comment]
v3.1.1 is live. Please update.
