### ISSUE TITLE
Fix default tests 

### ISSUE THREAD

**Issue by chinchang** [chinchang/web-maker#310]
Some tests come in by default with preact template. At least they should work.

**Comment by chinchang** [comment]
@DanielRuf you can assign this task to yourself.

**Comment by DanielRuf** [comment]
Not possible as I am not part / member of the org and project ;-)

**Comment by DanielRuf** [comment]
See https://github.com/chinchang/web-maker/pull/306/commits/e173e5a9755355a67c1e566f98b28476802a063f

**Comment by chinchang** [comment]
fixed.
