### ISSUE TITLE
Save as HTML button not working at all

### ISSUE THREAD

**Issue by HippieKiller** [chinchang/web-maker#313]
Hi, in WebMaker extension version 3.3.2 the "Save as HTML" button does nothing

**Comment by chinchang** [comment]
Just to confirm, you are using the Chrome extension, correct?

**Comment by HippieKiller** [comment]
After checking it out further it's silently failing due to undefined chrome.downloads:

Uncaught (in promise) TypeError: Cannot read property 'download' of undefined
    at downloadFile (https://github.com/chinchang/web-maker/blob/master/src/utils.js#L216)

I've never made an extension so I'm not much help with this, but from what I gather chrome.downloads is usually defined, I don't know why it is undefined. I tried "allow access to file URLs" option in Chrome extensions in case it was permissions related but that didn't help either

**Comment by HippieKiller** [comment]
Hi, after much head-scratching, and messing with messages, I found the fix was simple.

You just need to add "downloads" to permissions in manifest.json and the save as window appears as expected :)

**Comment by chinchang** [comment]
@HippieKiller Thanks for debugging this! Actually the "downloads" permission is already listed in manifest.json under `optional_permissions`. I don't why this has suddenly stopped working. For now I have made it fallback to the app's approach for downloading even in the extension. Should work in the latest release 3.4.0.

**Comment by HippieKiller** [comment]
Sure, no problem, I learned some new things about Chrome extensions and I'd never looked at Preact before so all is good :)

The chrome.downloads.download does only work after adding downloads in permissions, but not optional_permissions, I tried for ages to get chrome.tabs.onMessage handlers to work too, but the anchor download works in all cases so probably a wise move.
