### ISSUE TITLE
Here a small detail

### ISSUE THREAD

**Issue by leninalbertolp** [chinchang/web-maker#315]
![low opacity](https://user-images.githubusercontent.com/8427648/43435161-bba18cd2-944c-11e8-811d-bcac3c6840f8.png)
Here a small detail, the font color in the libraries selector and in the settings is too clear or the background has a very low opacity.

**Comment by chinchang** [comment]
Oops! That's a bug. Thanks for reporting @leninalbertolp :)

**Comment by chinchang** [comment]
fixed in latest release 👍
