### ISSUE TITLE
When I try to import local projects, error occurred.

### ISSUE THREAD

**Issue by awguo** [chinchang/web-maker#316]
Every time when I click the 

Yes, please import.

This error occurs:

```
	App.prototype.importCreationsAndSettingsIntoApp = function importCreationsAndSettingsIntoApp() {
		var _this16 = this;

		this.mergeImportedItems(this.oldSavedItems).then(function () {
			(0, _analytics.trackEvent)('fn', 'oldItemsImported');
			_this16.dontAskToImportAnymore();
		});
	};
```

**Comment by chinchang** [comment]
Can you please confirm that you are trying to import the file that you exported from Web Maker itself?

**Comment by cristianofromagio** [comment]
It seems to be the same error here.
System: Ubuntu 18.04 / Firefox 63.0
Flow: save file local without login, then Github auth, and below error appears when clicking "Yes, please import" in the "Import your creations in your account" dialog.
```
TypeError: this.mergeImportedItems is not a function[Learn More] script.js:80:177583
	uv7j/ie</t.prototype.importCreationsAndSettingsIntoApp https://webmakerapp.com/app/script.js:80:177583
	<anonymous> self-hosted:975:17
	f https://webmakerapp.com/app/vendor.js:1:572771
```

**Comment by chinchang** [comment]
fixed in 3.6.1

**Comment by reggaeman1** [comment]
I tried to setup your source code but it's not working 
How can I set your source code up please

**Comment by chinchang** [comment]
@reggaeman1 What exactly isn't working? Any errors? Can you open a new issue for this please?

**Comment by reggaeman1** [comment]
NO @chinchang is not and issue i just need some guide on how to run your code
and i also suggest a  **counter timer** for those that would love to test their coding speed
