### ISSUE TITLE
Preview Window Pixels Display 

### ISSUE THREAD

**Issue by jarisgv** [chinchang/web-maker#317]
Hello!
I'd like to suggest a feature to display the preview window pixels for  helping users with media query breakpoints.
This is how the featured would look like:
![180813-request-live-pixels-display](https://user-images.githubusercontent.com/19142770/44056295-32e31a96-9f1e-11e8-9965-6c2d18faae6c.jpg)
Thnx a lot.
Jaris GV
Brazil

**Comment by chinchang** [comment]
Great suggestion. I'll add it.

**Comment by jarisgv** [comment]
Thanks a lot @chinchang 
Greetings from Brazil.
:brazil:
