### ISSUE TITLE
Console disappears on changing layout in detached mode

### ISSUE THREAD

**Issue by jimmck** [chinchang/web-maker#319]
Detaching preview screen and changing display layout loses the console. MAC Sierra in Chrome

**Comment by chinchang** [comment]
When in detached mode, console stays in the code window as shown below:

![console-hidden](https://user-images.githubusercontent.com/379918/44111644-a77c900a-a020-11e8-877f-3a42b7a83c58.png)

**Comment by jimmck** [comment]
Hi
I know hence the issue. I thought it might be some weird issue using Duet and 2 other monitors on Mac but no. Trying to duplicate exact conditions. But refreshing chrome browser instance can fix. Also closing separate window and refresh seems to work. But console pane can go away when you change the display ordering of remaining web-maker windows. Thanks for responding!

Jim

**Comment by jimmck** [comment]
Hi,
Been testing more. Its not Kontra. If you detach the preview screen and then change the screen layout of the HTML, CSS and JS panes; the console disappears. If I close the detached preview window and change the screen layout again the console comes back.

System Software Overview:

  System Version:	macOS 10.12.6 (16G1510)
  Kernel Version:	Darwin 16.7.0
  Boot Volume:	Macintosh HD
  Boot Mode:	Normal
  User Name:	James McKearney (jimm)
  Secure Virtual Memory:	Enabled
  System Integrity Protection:	Enabled
  Time since boot:	2 days 23:23

Hardware Overview:

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro11,1
  Processor Name:	Intel Core i5
  Processor Speed:	2.4 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	3 MB
  Memory:	8 GB
  Boot ROM Version:	MBP111.0146.B00
  SMC Version (system):	2.16f68
  Serial Number (system):	C02MNHXTFH00
  Hardware UUID:	2C9AB132-9DF2-5EEB-BC98-79BC05CBD80C

Google Chrome is up to date
Version 68.0.3440.106 (Official Build) (64-bit)

Regards,
Jim

Tell me what you need!!

**Comment by chinchang** [comment]
Thanks for the detailed information @jimmck. I'll look more into this.

**Comment by chinchang** [comment]
Fixed in v3.4.2
