### ISSUE TITLE
Stop script

### ISSUE THREAD

**Issue by muiris** [chinchang/web-maker#320]
Hi,
Is it possible to stop your code from running or pause? 

I've just loaded a project that was OK yetserday but a loop keeps running and I can't even edit the code as it slows the broswer down so much.

**Comment by chinchang** [comment]
Hi @muiris 
Are you using the extension or the web app?

**Comment by muiris** [comment]
the web app on Firefox 52.5.0

**Comment by muiris** [comment]
Thanks for that. Love the app btw :+1:
