### ISSUE TITLE
Help understanding project structure

### ISSUE THREAD

**Issue by mobitar** [chinchang/web-maker#323]
Hello, I'm trying to run this project locally and a little confused on the project structure. 

The main thing that's confusing is me the difference between src, build, and app folders. I understand that src is the actual raw code. But I'm not sure why some files are duplicated inside of the app folder. It seems that this directory is not dynamically generated like the build directory.

For the app directory, I'm able to open index.html, but not statically as a file. I have to start up a server, otherwise, it complains about loading screenlog. My goal is to be able to run this project statically without a server (just open index.html directly and it works.)

As for the build directory, usually I expect it to contain everything to run the project in a standalone environment. However, opening index.html inside the build directory seems to be referencing files from a "lib" directory, which does not exist inside.

Hoping you can shed some insight as to what are the purposes behind each folder.

**Comment by HippieKiller** [comment]
I had issues trying to get the extension to run, and in the end I just copied all the files that are not bundled from src into the build directory, such as the lib directory, and all html files, images, fonts and icons.

**Comment by mobitar** [comment]
Turns out what I was looking for was "gulp release". That built all the assets and the app folder. Strange that it was commented out from the gulp file.

**Comment by nherbaut** [comment]
@mobitar that's what I was looking for, thanks...

**Comment by chinchang** [comment]
Sorry folks, I should definitely document the development workflow. Opened an issue for that -> #325.
For some quick overview:
- **src** - Source files for editing. 
- **app** - Built files from which the web app run. This gets statically served over HTTPS.
- **build** - Temporary folder generated by Webpack during release. Contains the webpack bundles.

To get the app running on your local machine:
- `yarn install`
- `yarn run dev`
This will start the app on a local server.

**Comment by chinchang** [comment]
Made the contribution guide better -> https://github.com/chinchang/web-maker/blob/master/CONTRIBUTING.md
