### ISSUE TITLE
Editor keeps reverting back to the default arrangement

### ISSUE THREAD

**Issue by jazoom** [chinchang/web-maker#33]
I like having the view down the bottom so I have plenty of vertical space for HTML/CSS/JS. Why must it revert to the default view every time I open a new tab? It forces me to keep re-adjusting it.

**Comment by jazoom** [comment]
Okay, now it seems to be saving my preference. Nice job. I'm not sure why it wasn't working before.

**Comment by jazoom** [comment]
But then again, it still reverts the heights of the windows that I have set....

**Comment by jazoom** [comment]
I've never developed a Chrome extension before, but is it possible to have the bookmarks bar up there with your extension (and not with every page), just like the default Chrome new tab?

**Comment by chinchang** [comment]
You mean the extension shouldn't show up on every tab? That can be done from the settings button in the right bottom corner in the extension.

**Comment by jazoom** [comment]
No. When your extension is the "New tab" then the bookmarks bar is no longer there, which is arguably the most important thing on the "New tab".

In Chrome's settings you can make the bookmark bar always show, but that is distracting when browsing since it usually has many colours and it takes up vertical space.

**Comment by chinchang** [comment]
Oh I see. Hmm, I guess the permanent bookmarks bar is the option for now. Or if its too critical to show bookmarks bar in the new tab only, then you can stop Web Maker from showing in new tab and revert to google's default new tab page. Web Maker can always be accessed from icon in the top right.

**Comment by jazoom** [comment]
That's actually what I've done. I don't use Web Maker every session so it's no big deal to click the icon. Thanks again for a great extension!
