### ISSUE TITLE
Browser freezing and laptop overheating while typing infinite loops still not fixed

### ISSUE THREAD

**Issue by jkantner** [chinchang/web-maker#34]
In the middle of typing a `for` or `while` loops in JavaScript, the browser froze and nearly set my computer on fire. Please focus more on fixing this. Thanks!

**Comment by chinchang** [comment]
Infinite loop protection has been added in version 2.0. Can you please check if you are on the latest version?

**Comment by jgresalfi** [comment]
It's happening to me too (version 2.0.1) and I can't reload the extension because it keeps trying to reload my infinite while loop. Otherwise, I love web maker, very nice work @chinchang ! Thank you!

**Comment by chinchang** [comment]
@jgresalfi @jkantner Would it be possible to post your script code here? That would really help me in debugging the issue.

**Comment by jgresalfi** [comment]
I lost my original code.

**Comment by jrhalchak** [comment]
I just experienced this (still trying to recover).

I just literally had two variables I was going to increase the value of in a while loop... all I got through was `while(newTop < 100)` and then it started locking up and now it's saved that as a loop and it takes over every time I open the extension.

**Comment by chinchang** [comment]
@jrhalchak I'll definitely look into this issue and also add a mode to disable script execution. Meanwhile this is how you can do it manually:

1. Open Web Maker's options page -> chrome-extension://lkfkkhfhhdkiemehlpkgjeojomhpccnh/options.html
2. Open chrome developer console
3. Run `chrome.storage.sync.set({ autoPreview: false });`

Now try opening Web Maker. Let me know.

**Comment by jrhalchak** [comment]
@chinchang sorry I didn't check back after I wrote the comment... I was able to disable the auto-opening of the last creation and disable vim mode which allowed me to randomly select and delete the code quicker.

Thanks for the steps though, it'll help in the future.

**Comment by jrfoxw** [comment]
@chinchang I am having similar issues I wrote about it in Gitter. 
I was in the web app and _thought I had fixed it_. I'm still having the issue in the **extension** here is what I have in console. 

![image](https://user-images.githubusercontent.com/13408697/37254711-acdfbb9e-250f-11e8-8a3a-d46e60bba44c.png)

**Comment by jrfoxw** [comment]
I really need some help on this as I use this quite frequently :(

**Comment by chinchang** [comment]
Hey @jrfoxw Can you please join me on Gitter and I'll help you out off the issue. I sent you a ping there.
