### ISSUE TITLE
SASS does not work in Chrome, but in Firefox it works fine

### ISSUE THREAD

**Issue by jarisgv** [chinchang/web-maker#344]
Hello @chinchang 

I don't know if it's a bug or something wrong here, but I thought SASS didn't work in Web Maker Offline so I tried to open it in Firefox yesterday and saw that it works fine. 
But in Chrome [Version 70.0.3538.77 (Official Build) (64-bit)] it fails. It shows only a blank preview. 
## Screenshot - SASS in Firefox:
![image](https://user-images.githubusercontent.com/19142770/48009231-6249fb80-e102-11e8-8a20-10ad9084d9c3.png)

## Screenshot - SASS in Chrome (v.70)
![image](https://user-images.githubusercontent.com/19142770/48009325-ad640e80-e102-11e8-9cf4-b1d0f7e77b11.png)

Best wishes!
:brazil:

**Comment by jarisgv** [comment]
PS: Web Maker App Online [https://webmakerapp.com/app] works fine in both browses.
:-D

**Comment by chinchang** [comment]
@jarisgv I noticed that the url on which you are running the app is a local file url. Ajax requests don't work on local file urls so this and multiple other things won't work.
I am curious though, why running it this way?

**Comment by jarisgv** [comment]
@chinchang,
Interestingly it works perfectly in Firefox, even working on the offline app.
Well, answering your question about why working this way, well, is a personal way of avoiding distractions. Sometimes I turn off the wi-fi to work for hours, because notifications of new scientific studies and other information are an addiction. You know, some people cannot resist a cup of coffee, others a new quantum physics video. Lots of Laugh.
:smile: :smile: :smile:

**Comment by jarisgv** [comment]
@chinchang 
Well, the online app is sensitive to cache cleaning getting unavailable if I have to do so for some reason. About the extension, I even used it for some time. But since it is not possible to create templates yet, I have to create them and add them manually every time I start a project, importing .jsons saved with my preferences. But this is a process that makes the user experience unsatisfactory. 
With the project offline, I can add them to the template list. But I'm keeping up with the tasks on the 4.0 project board and I believe that with the new changes to come, I will certainly start using one of the official options.
Best wishes.
:brazil:
