### ISSUE TITLE
screenlog.js does not load when running in dev mode

### ISSUE THREAD

**Issue by titaniumbones** [chinchang/web-maker#355]
## Meta info

bug for git version b006b4849e52115d06bfab2eedf9e8a1d719c2de in locally-run web app

## Description

`screenlog.js` does not load when running a local instance of web-maker in dev mode with `yarn run dev`. Currently, the script tag generated in `utils.js` does not point to a served file when in development mode. I have fixed it for myself with the attached patch, but that probably breaks the development version. I don't know anything about preact or react but I think a better fix is probably to set a switch somewhere in preact.config.js? 

``` diff
---
 src/utils.js | 10 +++++++---
 1 file changed, 7 insertions(+), 3 deletions(-)

diff --git a/src/utils.js b/src/utils.js
index ba6c662..08f461b 100644
--- a/src/utils.js
+++ b/src/utils.js
@@ -349,9 +349,13 @@ export function getCompleteHtml(html, css, js, item, isForExport) {
 			'<script src="' +
 			(chrome.extension
 				? chrome.extension.getURL('lib/screenlog.js')
-				: `${location.origin}${
-						window.DEBUG ? '' : BASE_PATH
-				  }/lib/screenlog.js`) +
+				: `/lib/screenlog.js`) +
+			// (chrome.extension
+			//  ? chrome.extension.getURL('lib/screenlog.js')
+			//  : `${location.origin}${
+			// 			window.DEBUG ? '' : BASE_PATH
+			// 	  }/lib/screenlog.js`) +
+
 			'"></script>';
 	}
 
-- 
2.19.1
```

**Comment by chinchang** [comment]
Yes, actually the app is meant to be run on `/app` path unless a debug/dev flag is switched on. If you are running your own copy of Web Maker on local system then you can fix this by changing this line in `utils.js`: https://github.com/chinchang/web-maker/blob/master/src/utils.js#L18 to:

```
export const BASE_PATH = '/';

```
