### ISSUE TITLE
Settings: indetermined checked radio-button

### ISSUE THREAD

**Issue by SynCap** [chinchang/web-maker#365]
## Meta info

- Is this a bug or suggestion?: seems to be a bug
- Version (click on help icon in footer): 3.6.2
- Context - Web app, Chrome extension or both?: both

![image](https://user-images.githubusercontent.com/1856986/53075427-1e032f80-3528-11e9-823d-73ff32d6fe94.png)
both radio are clean

**Comment by chinchang** [comment]
Strange! Thanks for reporting. I'll look into this.

**Comment by chinchang** [comment]
fixed in 4.0
