### ISSUE TITLE
Please do not replace the new tab - it's very annoying

### ISSUE THREAD

**Issue by georgeciobanu** [chinchang/web-maker#37]
I almost uninstalled it because of that.

**Comment by chinchang** [comment]
I hope you got to the setting for turning that off?

Are you saying that new tab replacement should be optional instead of default?

**Comment by georgeciobanu** [comment]
Yes and absolutely yes.

Sent from a device with a tiny keyboard
c: 650.691.3178

**Comment by shubhamnishad97** [comment]
I also find that annoying . new tab replacement should be optional or you can show a popup explaining the setting.

**Comment by chinchang** [comment]
For the records, had a poll on this -> https://twitter.com/webmakerapp/status/831763556282556416
