### ISSUE TITLE
transform: rotate not functioning in selectors

### ISSUE THREAD

**Issue by CodeThePeace** [chinchang/web-maker#377]
Alas!

```
transform:rotate(20deg);
```
is not working in the selectors as it should. 
 
![Screenshot 2019-03-12 at 4 48 22 PM](https://user-images.githubusercontent.com/48228155/54243748-009e0180-44e7-11e9-9f3d-bf2cd123bde2.png)
![Screenshot 2019-03-12 at 4 47 39 PM](https://user-images.githubusercontent.com/48228155/54243760-05fb4c00-44e7-11e9-919e-3d1dec5212f3.png)

**Comment by chinchang** [comment]
Transform doesn't work on inline elements. Its how it works in CSS. Read more on following page -> https://stackoverflow.com/questions/14883250/css-transform-doesnt-work-on-inline-elements

Closing this. Feel free to open if you feel its a Web Maker bug.
