### ISSUE TITLE
Code Folding

### ISSUE THREAD

**Issue by pixelspring** [chinchang/web-maker#38]
The ability to fold blocks of code would be very useful:

_Before:_
![screen shot 2017-01-10 at 14 37 56](https://cloud.githubusercontent.com/assets/276487/21810146/769a8b34-d742-11e6-9de2-7ad1c0e378cb.png)

_After:_
![screen shot 2017-01-10 at 14 38 11](https://cloud.githubusercontent.com/assets/276487/21810150/79e8aa1e-d742-11e6-882a-a23785bf71e3.png)

**Comment by chinchang** [comment]
live in 2.1.0
