### ISSUE TITLE
Missing Google Analytics Event Tracking for 'usingPreview' Action 

### ISSUE THREAD

**Issue by mwpeng** [chinchang/web-maker#382]
## Meta info

- Is this a bug or suggestion?: Bug
- Version (click on help icon in footer): 3.6.2
- Context - Web app, Chrome extension or both?: Web app

By reading the code,   the condition used for firing tracking event would only happen once in a lifetime.

**Comment by chinchang** [comment]
That is actually intentional :) Its meant to represent a user actually writing some code in a single session. It just needs to fire once if a user writes code (which I check with 4 edit counts) in a single session.
