### ISSUE TITLE
Files Saved locally lost!

### ISSUE THREAD

**Issue by CodeThePeace** [chinchang/web-maker#384]
## Meta info

- Is this a bug or suggestion?: Bug
- Version (click on help icon in footer): 4.0
- Context - Web app, Chrome extension or both?: Web app

Greetings,

I have experienced a very frustrating problem with the change over to 4.0.  I am interested in the new features, but with the changeover, all my files in progress were lost!  And the files that I tried to save locally are not apparent.

**Comment by chinchang** [comment]
Hi! For locally saved files, you'll need to export from old app and import in new app manually. Here is how you can export and import -> https://medium.com/web-maker/importing-exporting-your-creations-d92e7de5c3dc

**Comment by CodeThePeace** [comment]
No, this seems to have been only a temporary problem.  This seems to have been resolved.

There was also an unusual issue were the autosave didn't save a short bit of HTML, and when the browser was refreshed to test page, entire session was lost.  I have not attempted to repeat this so I can not confirm this as an error.  

Thank you.

**Comment by chinchang** [comment]
Oke. Closing the issue. Please feel free to open a new issue of required.
