### ISSUE TITLE
Firefox Windows Ctrl+Shift+P keyboard shortcut does not work

### ISSUE THREAD

**Issue by myfonj** [chinchang/web-maker#385]
## Meta info

- Bug (but likely in Firefox), Suggestion (use F1 as well)
- Version: 4.0.0
- Context: Web App

### Headsup
<kbd>Ctrl</kbd><kbd>Shift</kbd><kbd>P</kbd> in Firefox/Windows [is reserved for opening Private window](https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly#w_windows-tabs) and seems unlikely to be prevented from page script (IMBW).

### Suggestion
VSCode uses <kbd>F1</kbd> as default alternative hotkey for command palette, and this key seems to be free, so it might be workaround-ish solution.

**Comment by chinchang** [comment]
live in v4.0.1 web app
