### ISSUE TITLE
I lost everything, when changed the edit to monoco editor

### ISSUE THREAD

**Issue by nabazgharib** [chinchang/web-maker#387]
## Meta info

- Is this a bug or suggestion?: bug
- Version (click on help icon in footer): Web Maker4.0.0
- Context - Web app, Chrome extension or both?: Chrome app

I wrote some codes, I tried to change the editor to Monaco editor by clicking on the option button, but, right away, all my codes are gone. Fortunately I have the old app running on an other tab, so I did copy and paste again.

**Comment by chinchang** [comment]
You have mentioned Chrome extension, but 4.0.0 is not yet available on Chrome extension. I suppose you mean to say web app, correct?
I'll check this issue right away.

**Comment by nbaghm** [comment]
> You have mentioned Chrome extension, but 4.0.0 is not yet available on Chrome extension. I suppose you mean to say web app, correct?
> I'll check this issue right away.

Yes, you are right, I corrected it.
