### ISSUE TITLE
#rrggbbaa and #rgba color notations not working in SCSS

### ISSUE THREAD

**Issue by andrienko** [chinchang/web-maker#393]
## Meta info

- Is this a bug or suggestion?: a bug
- Version (click on help icon in footer): 4.0.0
- Context - Web app at https://webmaker.app/app/

## The problem

In SCSS, something like this:
```
body {
  background: #0004;
}
```
does not work (css disappears entirely).

It works fine in either CodePen and manually configured SCSS. Also it works fine in plain CSS, as modern browsers support it, and in LESS.

**Comment by chinchang** [comment]
Hi @andrienko 
I tried replicating the issue, but it seems to be working. Here is a screenshot:
![Screenshot 2019-04-15 23 12 48](https://user-images.githubusercontent.com/379918/56153563-1914a680-5fd4-11e9-8c58-c3f27c32ab34.png)

Just curious, doesn't even refreshing the app help?

I would request you to please make a screen recording of the issue if possible to understand what exactly is happening w.r.t "css disappears entirely". Thank you.

**Comment by andrienko** [comment]
Hi @chinchang 
No, even refreshing does not help, I afraid :<

The browser is Chrome on OSX. AdBlocks and other stuff are disabled. I am not behind any proxy.

Works just fine for CSS and LESS. Strangely, it works fine for `color` property in scss, but does not for, say, `background` and `box-shadow`.

![PFCujxP3xr](https://user-images.githubusercontent.com/6045971/56206432-173ef780-6055-11e9-9400-8926ff4b2d08.gif)

**Comment by chinchang** [comment]
I'll update the SASS compiler and see if that fixes this.

**Comment by chinchang** [comment]
fixed in v4.0.1 web app
