### ISSUE TITLE
No LESS/SCSS syntax highlighing

### ISSUE THREAD

**Issue by andrienko** [chinchang/web-maker#394]
## Meta info

- Is this a bug or suggestion?: a bug
- Version (click on help icon in footer): 4.0.0
- Context - Web app at https://webmaker.app/app/, both CodeMirror and Monaco modes

## The issue
Apparently, when using LESS/SCSS, the editor still uses its CSS mode, as it highlights child selectors as faulty and single-line comments do not work:

CodeMirror:
![CodeMirror](https://user-images.githubusercontent.com/6045971/56092092-293b6180-5ec0-11e9-8e31-a09a81fde4e3.png)
Monaco:
![Monaco](https://user-images.githubusercontent.com/6045971/56092110-60117780-5ec0-11e9-95ac-a10806ec1d90.png)

**Comment by chinchang** [comment]
this is fixed in latest version.
