### ISSUE TITLE
Variable Already Declared error when trying to run script

### ISSUE THREAD

**Issue by ozjerry** [chinchang/web-maker#395]
## Meta info

- Is this a bug or suggestion?: Bug
- Version (click on help icon in footer): 3 and 4
- Context - Web app, Chrome extension or both?: Web App

When running a script that is looping, using 'requestAnimationFrame' in my instance, the script runs fine the first time. But any attempt to restart the script results in an error saying that the variables have all been declared before. It's as if it's trying to run a new script before the old one has finished executing.

I only see the issue in the web app, both V3 and V4, but not in the Chrome Extension.

**Comment by ozjerry** [comment]
The following code shows the issue on my system:
`
-html-
<canvas width="400" height="300"></canvas>

-Javascript-
const canvas = document.querySelector('canvas');
const ctx = canvas.getContext('2d');
const width = canvas.width;
const height = canvas.height;
const step = 2;

function draw() {
  requestAnimationFrame(draw);
  
  ctx.fillStyle = 'rgb(50,50,50)';
  ctx.fillRect(0,0,width,height);
  
  for(let y=0; y<height; y+=step) {
    for(let x=0; x<width; x+=step) {
      let rgb = Math.round(Math.random() * 255);
      ctx.fillStyle = `rgb(${rgb},${rgb},${rgb})`;
      ctx.fillRect(x,y,step,step);      
    }
  }
}

draw();
`

If I make a change to the code and then click 'Run' to execute it I get the following error:
Uncaught SyntaxError: Identifier 'canvas' has already been declared

**Comment by chinchang** [comment]
Hi @ozjerry 
I was able to reproduce the issue on my end. I'll fix this and update here. Thanks for reporting.

**Comment by ozjerry** [comment]
Thanks for the quick response. I'll leave it with you.
Cheers

**Comment by chinchang** [comment]
fixed in v4.0.1 web app
