### ISSUE TITLE
Mouse and Keyboard Events not Working

### ISSUE THREAD

**Issue by ozjerry** [chinchang/web-maker#399]
## Meta info

- Is this a bug or suggestion?: Bug
- Version (click on help icon in footer): 4
- Context - Web app, Chrome extension or both?: Web App

Any keyboard or mouse event throws an error in version 4. The error can be demonstrated with just one line of javascript:

`window.addEventListener('click', (e)=>{
  console.log(e);
});`

The same thing happens if a keydown event is added. I have also tested mouseclicks on a div element, which also fails. 
The same code works fine in version 3.

**Comment by ozjerry** [comment]
This is the error text:

`"Error: Failed to execute 'postMessage' on 'Window': MouseEvent object could not be cloned. at sendLog (https://webmaker.app/app/lib/screenlog.js:1:414) at proxyCallback (https://webmaker.app/app/lib/screenlog.js:1:2904) at https://webmaker.app/app/lib/screenlog.js:1:899 at console.e (https://webmaker.app/app/lib/screenlog.js:1:1394) at console.log (https://webmaker.app/app/lib/screenlog.js:1:1879) at HTMLDivElement.<anonymous> (userscript.js:3:44)"`

**Comment by chinchang** [comment]
Issue while doing a `console.log`. Will be fixed in coming version.
