### ISSUE TITLE
Usage in Google Chome Canary fails to resolve and throws console log messages. Content Security Policy.

### ISSUE THREAD

**Issue by c835722** [chinchang/web-maker#40]
Thanks for you plugin. Like it!

Google Chrome works fine for me. Chrome Canary seems to have a tighter content security policy I assume.

Here is an example to reproduce using Vue.JS.

![2017-01-15_10-52-13_02](https://cloud.githubusercontent.com/assets/1875669/21959093/c793e702-db10-11e6-9833-697e1e3fe744.png)

Tried this via "Add library" and via HTML native fashion as per screen print.

Browser : Chrome Canary v57.0.2981.

**HTML**
```
<div id="app">
  {{ message }}
</div>
```

**JS**
```
var app = new Vue({
  el: '#app',
  data: {
    message: 'Hello Vue!'
  }
})
```
as per example [here](https://vuejs.org/v2/guide/).

**Comment by chinchang** [comment]
This is because of change in content security policies in Chrome canary. Duplicate of #39.

FYI, this is in progress. For now you can use Web Maker in Chrome stable.

**Comment by nikkwong** [comment]
Doesn't seem to work in chrome stable FYI

**Comment by chinchang** [comment]
@nikkwong Are you using any external JavaScript library?

**Comment by xt0rted** [comment]
I'm having the same issue when I add `<script src="https://js.stripe.com/v3/"></script>` to try mocking up a payment form that uses [Stripe Elements](https://stripe.com/docs/elements).

Chrome 57.0.2987.133

Full error
> Refused to load the script 'https://js.stripe.com/v3/' because it violates the following Content Security Policy directive: "script-src 'self' filesystem: http://localhost:* https://localhost:* https://ajax.googleapis.com https://code.jquery.com https://cdnjs.cloudflare.com https://unpkg.com https://maxcdn.com https://cdn77.com https://maxcdn.bootstrapcdn.com https://cdn.jsdelivr.net/ https://www.google-analytics.com 'unsafe-eval'".

**Comment by chinchang** [comment]
@xt0rted Please refer the comment here -> https://github.com/chinchang/web-maker/issues/39#issuecomment-287965061
