### ISSUE TITLE
Support More Programming Languages

### ISSUE THREAD

**Issue by JACB920** [chinchang/web-maker#405]
## Meta info

- Is this a bug or suggestion?:
- Version (click on help icon in footer):
- Context - Web app, Chrome extension or both?:

So, I'm a beginner using WebMaker, and since I like looking at other items on CodePen, DEV.to, and other websites, I would like support of other programming languages on Web Maker.

I know <?php ?> works, but it seems like Python doesn't work. So these are the languages I would like to see in Web Maker:

Haml
Rust
Scala
Swift
Python
Ruby on Rails
C++
C
Erlang
Go
R
Dart
Haskell
TypeScript
Kotlin

Thanks!

**Comment by chinchang** [comment]
Hi. Thanks for your feedback. Web Maker is currently focused only on providing a frontend playground for Web. As of now, there is no such plan to support other programming languages in the future.
