### ISSUE TITLE
console window can't resize

### ISSUE THREAD

**Issue by garuhester** [chinchang/web-maker#415]
console window can't resize，Version 2.9.6 is fine.

**Comment by chinchang** [comment]
You should upgrade to latest version -> 4.0.3

**Comment by garuhester** [comment]
yes,i upgrade to the 4.0.3 version, the console window still can't resize, it just can toggle, but it don't like the js or css window can resize. : )    it works on chrome.
![image](https://user-images.githubusercontent.com/23695326/71136301-57d3be00-223f-11ea-85f5-55f6742033d2.png)

**Comment by HGetz2024** [comment]
I have the same problem

**Comment by chinchang** [comment]
Seems to be working fine now. Please let me know if otherwise.
