### ISSUE TITLE
Command prompt

### ISSUE THREAD

**Issue by a-a-GiTHuB-a-a** [chinchang/web-maker#424]
I am in Web Maker, and I went to the console. I see this line on the bottom, almost like a command prompt. Can someone tell me how this works? Thank you!

**Comment by chinchang** [comment]
here is a short gif to explain it:

![wm-console](https://user-images.githubusercontent.com/379918/80872645-cf772680-8cd0-11ea-9eaf-9478c310bab4.gif)

hope it helps!
