### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by leninalbertolp** [chinchang/web-maker#425]
I just wanted to know if the project is still alive 🤔

**Comment by chinchang** [comment]
Yes! it is. I have recently started work for next major version - v5! :)

**Comment by leninalbertolp** [comment]
Great! I'm glad to hear that Web Maker is on its way

**Comment by leninalbertolp** [comment]
A final question, to collaborate with the translation in V5 you have to translate both files or only the .po
