### ISSUE TITLE
I can't log in with github or google.

### ISSUE THREAD

**Issue by JuanSerranoTech** [chinchang/web-maker#436]
## Meta info

I try to access the login with my github account and it is not possible.
This has been happening for a few days.
How can I fix the error?
Have I lost all my repositories?

Thanks for your time!

**Comment by chinchang** [comment]
I'll check it today itself

**Comment by chinchang** [comment]
fixed now. All data is intact, nothing to worry.

**Comment by JuanSerranoTech** [comment]
Oh! Thanks! ^^
