### ISSUE TITLE
How to use local image as image source?

### ISSUE THREAD

**Issue by romelordinario** [chinchang/web-maker#438]
Hi, is there a way to use image from my local machine?

example:
![image](https://user-images.githubusercontent.com/13159597/99952978-7d583880-2dbb-11eb-8307-f62af0c1801a.png)

**Comment by chinchang** [comment]
Right now the only way is to host it somewhere (eg. imgur etc) and use the hosted url. Else you can run a local server and get the image served on a HTTP url to use it inside web maker.

**Comment by chinchang** [comment]
Now you can with the newly added PRO features. Checkout the app today!
