### ISSUE TITLE
Why Google Analytics?

### ISSUE THREAD

**Issue by der-On** [chinchang/web-maker#439]
What is the purpose of having google analytics in this tool?

As it is an offline tool it provides better privacy then comparable online tools, which would be my very first consideration to use it.

Please elaborate why you are including GA in it? If you only want usage statistics, please consider moving to a privacy and GDPR respecting analytics provider.

**Comment by chinchang** [comment]
Hi @der-On 
The reason for having GA is just to get aggregated analytics about the usage of various features inside the app. And beyond that sometimes there are sudden surges of traffic which I should know.

As for being an offline tool, GA would automatically not work when being used offline :)
I can try looking into privacy-focused tools. Any recommendations?

**Comment by der-On** [comment]
@chinchang Thank you for beeing open about that.

Privacy respecting tools I know would be https://matomo.org/ and https://plausible.io/
Both can be self hosted and are open source. Plausible is very simple and even does not require cookies. Matomo is a fully fledged analytics tool comparable to GA and can be made GDPR compatible with some simple settings.

**Comment by der-On** [comment]
@chinchang Here are some more https://switching.software/replace/google-analytics/

**Comment by chinchang** [comment]
I tried Plausible. It seems very basic. You cant have custom events fired and create funnels out of it. Its mostly for seeing traffic stats, which is the least important thing I would be interested in :)
Will try some more alternatives
