### ISSUE TITLE
Can't login [bug]

### ISSUE THREAD

**Issue by nathgit** [chinchang/web-maker#445]
## Meta info

- Is this a bug or suggestion?:
- bug
- Version (click on help icon in footer):
- 3.6.4
- Context - Web app, Chrome extension or both?:
web-app

EDITED: When I try to signup (using github) It opens the fiebase window briefly & starts trying to load but it closes. I have uMatrix but I disabled it globally after the first try with no change.

**Comment by chinchang** [comment]
Sorry for the late reply here, does this problem still persist?

**Comment by chinchang** [comment]
This is most likely due to cookies being disabled. Try enabling cookies on webmaker.app domain and it should work. Please reopen the issue if this still persists.
