### ISSUE TITLE
Installing on private school network

### ISSUE THREAD

**Issue by oleteacher** [chinchang/web-maker#460]
What a wonderful project, very simple to use.

I am wondering if there are instructions for building so we can host (or attempt to) on school local network? I understand it will need access to the net and can get IT department to allow through firewall.

The reason we can't just use online version is not all students have direct access to the net, just cannot be allowed.

Thanks in advance!

**Comment by chinchang** [comment]
Hello! How about using the Chrome extension then? That will require network access just once to install the extension. Then everything will run offline.

**Comment by oleteacher** [comment]
Hi there. The school district does not allow chrome extensions to be installed from online and will not in any way allow extensions to be imported (developer mode). It could cause security issues to allow 3rd party chrome extensions on the school network.

I wish it were easier to use projects like yours, but when dealing with school networks even a project like yours would have to go through IT security before install. People do not understand how secure most school networks are. Monitored constantly and shut down if any thing looks compromised.

**Comment by oleteacher** [comment]
Will close this since it does not seem feasible to use in our classroom.

**Comment by chinchang** [comment]
I'll update here if any advancements happen in this regards.
