### ISSUE TITLE
General Question: Where is the user generated code stored at?

### ISSUE THREAD

**Issue by inglesuniversal** [chinchang/web-maker#465]
Can storage location or bucket be configured?

Do I have to run and export the resulting build if I want to set up my own storage location?

Please explain how this works and if there is any storage limit or pricing involved?

**Comment by chinchang** [comment]
If you don't login, everything is stored locally in localstorage. But if you have logged in, then all your creations are stored on a cloud storage. Everything is free and no limit as of now.
