### ISSUE TITLE
The JS code format is invalid

### ISSUE THREAD

**Issue by fcwys** [chinchang/web-maker#468]
The JS code format is invalid, and the shortcuts cannot be used.

**Comment by chinchang** [comment]
Hi @fcwys 
Can you please elaborate on this. What do you mean by "format is invalid" and which shortcuts are not working?

**Comment by fcwys** [comment]
Click the format button. The JavaScript code is not formatted.

**Comment by fcwys** [comment]
have already been solved
`onClick:this.prettifyBtnClickHandler.bind(this,'js')`
