### ISSUE TITLE
couldn't build extension in local

### ISSUE THREAD

**Issue by IOLOII** [chinchang/web-maker#471]
## Meta info

- Is this a bug or suggestion?:
- Version (click on help icon in footer):
- Context - Web app, Chrome extension or both?:

## Chrome extension 
i clone this repo then i can run in dev, but i can't run build , i find in issues ,but no resolve, does this has some special setting to build?

but the default package.json  , after run build  i got this file system in all
![image](https://user-images.githubusercontent.com/34856171/135747673-a4c72379-99e2-4d6f-992f-16d3550ec3bb.png)

then i download webmaker chrome store extension, just compare there two folder system , i find something was not in build folder ,or not in src folder,
![image](https://user-images.githubusercontent.com/34856171/135747839-a4355f01-7e42-40eb-9f4b-e024ef36f7e4.png)

and also i find this paragraph in `CONTRIBUTING.md`  *Select the extension/ folder in the repo.*  , but  no `extension/ ` folder in the repo

so , how does this working? 

by the way: i can runing in dev  and get some self change
![image](https://user-images.githubusercontent.com/34856171/135747809-dcceacc2-5f44-4739-8a86-578bb5a164a1.png)

if there someone has same trouble , please help, this is a good repo , so i want use

**Comment by IOLOII** [comment]
when i install the extension by using run build , then this chrome get icon , i click this extension but got this err report:

![image](https://user-images.githubusercontent.com/34856171/135747949-5e00981e-f3d2-410c-9aa5-bd00a41fc3c8.png)

**Comment by IOLOII** [comment]
> which node version are you using?

node v10

**Comment by chinchang** [comment]
Use node 16
