### ISSUE TITLE
self closing tags not working

### ISSUE THREAD

**Issue by chhavi-khandelwal** [chinchang/web-maker#474]
## Meta info

- Is this a bug or suggestion?: bug
- Version (click on help icon in footer): 4.0.3
- Context -  Chrome extension 

<div/> does not behave as <div></div>. their position differs when they are absolutely positioned.

**Comment by chinchang** [comment]
Didn't get it exactly. What are absolutely positioned? Screenshot please :)
PS: Good to see you still using it. :)

**Comment by chhavi-khandelwal** [comment]
https://user-images.githubusercontent.com/5188325/139914016-90d73bdb-7e55-46e4-a090-ec2aa79e0ab0.mov

Attaching a file. Hope this helps!

**Comment by chinchang** [comment]
Ah I see. Well, 2 things here:
1. DIV isn't a self-closing element by standard
2. Web Maker simply puts your written HTML in the DOM, the final DOM created is how browsers do it. And from what I see, `<div />` is the same as `<div>` now. That is self-closing `div` is enclosing the tags after it. This is a browser behavior change it seems in the latest version of Chrome.

**Comment by chhavi-khandelwal** [comment]
aah! Thanks! Didn't know that.
