### ISSUE TITLE
top header buttons misaligned (v5)

### ISSUE THREAD

**Issue by chinchang** [chinchang/web-maker#498]
![image](https://user-images.githubusercontent.com/379918/157280950-aad6679d-8d94-4ec3-b8ac-50a84ee3bdaf.png)

**Comment by arnabsen1729** [comment]
So the issue was an overriding css property.

**Before:**
![image](https://user-images.githubusercontent.com/51032928/157293921-9daf335d-39e4-4ba3-b73e-38c206e0fd80.png)

**After:**
![image](https://user-images.githubusercontent.com/51032928/157294065-c6d787be-d265-4b50-a11f-8cc5bf4cbd29.png)

**Comment by chinchang** [comment]
@arnabsen1729 still don't see the exact root cause. The same styles apply on the production app too, but this issue isnt present there.
