### ISSUE TITLE
Add Cypress framework

### ISSUE THREAD

**Issue by chinchang** [chinchang/web-maker#513]
We should start adding e2e tests with Cypress.

**Comment by chinchang** [comment]
@arnabsen1729 List of tests we can have:
- type in some html, hit save. there should be something in the localstorage with "untitled.." in name
- change the creation title, it should auto save in localstorage. Also a toast should show up saying it was saved.
- Clicking "OPEN" should open the saved items pane.
- Saved items should show up in the saved items pane
- "Add Library" should open the add library modal. Selecting any library from dropdown should change the URL in the textarea fields. Selecting another library should add the URL in a newline in the textarea fields.

**Comment by arnabsen1729** [comment]
- [x] type in some html, hit save. there should be something in the localstorage with "untitled.." in name
- [ ] change the creation title, it should auto save in localstorage. Also a toast should show up saying it was saved.
- [ ] Clicking "OPEN" should open the saved items pane.
- [ ] Saved items should show up in the saved items pane
- [ ] "Add Library" should open the add library modal. Selecting any library from dropdown should change the URL in the textarea fields. Selecting another library should add the URL in a newline in the textarea fields.
