### ISSUE TITLE
Not allowed to navigate to filesystem URL

### ISSUE THREAD

**Issue by chinchang** [chinchang/web-maker#520]
### Discussed in https://github.com/chinchang/web-maker/discussions/519

<div type='discussions-op-text'>

<sup>Originally posted by **ronaldohoch** August  5, 2022</sup>
Hello, thank you for this beautiful app/extension!

Does one of you has seem these error: 
![image](https://user-images.githubusercontent.com/2287371/183078046-8bb46a64-0b73-425a-befe-4d66c7acbadd.png)

I'm using Brave Browser: `[Versão 1.42.86 Chromium: 104.0.5112.81 (Versão oficial) 64 bits](https://brave.com/latest/)`, yesterday was working... 😟</div>

**Comment by chinchang** [comment]
Hey everyone! Seems like they have introduced some new policy which is causing this.

While I investigate this, here is what I would recommend:
If you are already logged in, then good. Otherwise, please log in first of all and save all your creations in your account. Then go to https://webmaker.app/app/ and login again with your same account. You'll get all your creations on the web app.
Also, its recommended to switch to the web app anways since it has more features and works offline too.

I'll keep updating my findings here.

**Comment by pnsvk** [comment]
> Hey everyone! Seems like they have introduced some new policy which is causing this.
> 
> While I investigate this, here is what I would recommend: If you are already logged in, then good. Otherwise, please log in first of all and save all your creations in your account. Then go to https://webmaker.app/app/ and login again with your same account. You'll get all your creations on the web app. Also, its recommended to switch to the web app anways since it has more features and works offline too.
> 
> I'll keep updating my findings here.


Thank you for raising this issue.. Yes, I have been browsing if there is any solution to this issue that I started to face since a week.

Can you please let me know how the web-app would work offline too ? -- Coz, when the Wi-Fi is gone, I was not able to visit the web-app.

**Comment by chinchang** [comment]
> > Hey everyone! Seems like they have introduced some new policy which is causing this.
> > While I investigate this, here is what I would recommend: If you are already logged in, then good. Otherwise, please log in first of all and save all your creations in your account. Then go to https://webmaker.app/app/ and login again with your same account. You'll get all your creations on the web app. Also, its recommended to switch to the web app anways since it has more features and works offline too.
> > I'll keep updating my findings here.
> 
> Thank you for raising this issue.. Yes, I have been browsing if there is any solution to this issue that I started to face since a week.
> 
> Can you please let me know how the web-app would work offline too ? -- Coz, when the Wi-Fi is gone, I was not able to visit the web-app.

The web app should work offline, through a service worker. You need to open the app once with wifi...then next visits should work offline too.

Let me know if still you face issue.

**Comment by chinchang** [comment]
ref: https://chromestatus.com/feature/5816343679991808

**Comment by chinchang** [comment]
Getting fixed in manifest v3 of the extension.
Should be live by month end

**Comment by chinchang** [comment]
This is now fixed. JavaScript is working again in v6.3.3! 🎉
