### ISSUE TITLE
console error: script-src 'self'

### ISSUE THREAD

**Issue by sekedus** [chinchang/web-maker#526]
## Meta info

- Is this a bug or suggestion?: bug
- Version (click on help icon in footer): Web Maker 5.0.1
- Context - Web app, Chrome extension or both?: Chrome extension
- Chrome: 103.0.5060.134 (Official Build) (64-bit)

**Refused to load the script** 👇

![im4jNC](https://user-images.githubusercontent.com/25115799/206886146-8a7e5403-0676-4679-8314-3eda95a519ec.png)

**Comment by vinitsingh-13** [comment]
just reload the page or console it will go.

**Comment by chinchang** [comment]
Should be fixed now. Please re-open if still not working.
