### ISSUE TITLE
v2.2.1 export html does NOT include js

### ISSUE THREAD

**Issue by pleabargain** [chinchang/web-maker#53]
v.2.2.1
step to reproduce:
export 

1. html
2. open html in browser or on local server
3. html file does not contain js it contains a link to a temp file in chrome ergo js does not work

**desired behavior**
js is included in the html OR
js and other assets are exported into folder 
with index.html
e.g.
dir: index.html
dir dir file.js
dir dir photo.jpg
dir dir 2photo.jpg

video
https://youtu.be/Be_5dcqO_NI

on local machine
![image](https://cloud.githubusercontent.com/assets/640846/22290063/e7057a22-e30f-11e6-800a-eddfa98cdc21.png)
on codepen
![image](https://cloud.githubusercontent.com/assets/640846/22290069/ef0d814c-e30f-11e6-9516-9b62b024d31d.png)

**Comment by chinchang** [comment]
fixed in v2.2.2. Thanks for reporting @pleabargain :)

**Comment by pleabargain** [comment]
appears to be fixed in 2.2.2.
thank you!
