### ISSUE TITLE
can not remove library

### ISSUE THREAD

**Issue by patrickdegand** [chinchang/web-maker#530]
## Meta info

- Is this a bug or suggestion?: bug
- Version (click on help icon in footer): 5.0.1
- Context - Web app, Chrome extension or both?: Web app

once a library has been added with the "Add library" button, it can not be removed later, even when the library link is deleted in the popup window.

**Comment by chinchang** [comment]
confirmed that this is happening. Taking this up today. Sorry about the huge delay here :/
