### ISSUE TITLE
UX issue opening saved files you must click in a very specific place on the button

### ISSUE THREAD

**Issue by pleabargain** [chinchang/web-maker#54]
click open
saved files as buttons show up
you cannot click on text to open the file...
you must click on the blank area in the lower right of the button to open the file

desired behavior:
user can click anywhere in the button to open the saved file

here's the video
https://youtu.be/--3kuSYumMc

**Comment by chinchang** [comment]
Getting fixed in 2.2.2

**Comment by chinchang** [comment]
fixed in v2.2.2. Please update.

@pleabargain Thank you so much for taking out time and creating these detailed issues. Really appreciate it. This will help Web Maker become more awesome for everyone! Thanks for using it :)

**Comment by pleabargain** [comment]
@chinchang thank you for making the fixes so fast! Good luck with your project!
