### ISSUE TITLE
Project not saving

### ISSUE THREAD

**Issue by JAVAHTML1** [chinchang/web-maker#543]
## Meta info

- Is this a bug or suggestion?: Bug
- Version (click on help icon in footer): 5.0.3
- Context - Web app, Chrome extension or both?: Both

Bug: My project is not saving. I am using both the web app and the chrome extension and neither works. I have version 5.0.3

**Comment by chinchang** [comment]
Is it just one particular project that is not saving or none of them is saving? Also, can you check the console if there is any error logged while saving please?
