### ISSUE TITLE
Tab key not working in JS editor when using CodeMirror

### ISSUE THREAD

**Issue by nhogle** [chinchang/web-maker#546]
## Meta info
- bug
- Version 5.0.3
- Context:  Web app (and probably Chrome Extension, but I did not test)
- Chrome Version: 116.0.5845.188

The `Tab` key does nothing when using the default editor, CodeMirror.  This is due to a logical bug in the code, whereby the Emmet option check will short-circuit the logic that should actually handle the `Tab` keyboard key.

**Comment by nhogle** [comment]
@chinchang : Please see PR #547.  Thank you!

**Comment by chinchang** [comment]
merged in master. Deployed on web app. Chrome extension will be published soon.

**Comment by nhogle** [comment]
@chinchang That was so quick, thank you! :)
