### ISSUE TITLE
Detatched Preview is referencing non-existent style.css file, detached preview iframe is only 300px x 150px

### ISSUE THREAD

**Issue by nhogle** [chinchang/web-maker#548]
## Meta info

- Bug
- Version 5.10
- Context - Web app

It looks like the `preview.html` should probably be referencing the bundled css file? Either that, or we just need to deploy the `src/style.css` file? If you look at the [preview.html](view-source:https://webmaker.app/app/preview.html) on the production site, we see:
```html
<link rel="stylesheet" href="style.css">
<body>
	<iframe src="about://blank" frameborder="0" id="demo-frame" allowfullscreen></iframe>
	<script src="detached-window.js"></script>
</body>
```
But the main app [index.html](view-source:https://webmaker.app/app/) has:
```html
<html>
  <!-- ... -->
  <head>
    <!-- ... -->
    <link href="./bundle.eef2b.css" rel="stylesheet">
  </head>
  <!-- ... -->
</html>
```

The result is that the embedded iframe in the detached preview is only 300px by 150px, not filling the preview window.  

The reference to `style.css` produces a 404 error, since there is no `/app/style.css` file on the production site. Perhaps the `src/style.css` file should be deployed? It looks like `gulpfile.js` used to include it in the deliverables, but then it got [commented out](https://github.com/chinchang/web-maker/blame/master/gulpfile.js#L90).

@chinchang : Your thoughts?

**Comment by chinchang** [comment]
This is fixed now. Thanks for reporting, Nick!
The style.css wasn't actually necessary...was working before last release because of a cache. Last release removed the file and hence broke the preview. The required styles are now inlined.

**Comment by chinchang** [comment]
@nhogle Also, one thing I am curious about - do you use web app or chrome extension?

**Comment by nhogle** [comment]
Great thank you for getting this fixed!!

I have been using the web app, it has been great! I'm curious what benefits
I might get from using the chrome extension instead?

Cheers,
-Nick

**Comment by chinchang** [comment]
Web app has more features, so you are good :)
