### ISSUE TITLE
Auto save issue

### ISSUE THREAD

**Issue by atubo-1** [chinchang/web-maker#551]
## Meta info

When I try to open the file after automatically saving it, the data is not saved.
I've tried logging out and logging in several times, but it doesn't work.
How can I save it?

- Is this a bug or suggestion?:
- Version (click on help icon in footer):
- Context - Web app, Chrome extenss this a bug or suggestion?:
- Version (click on help icon in footer):
- Context - Web app, Chrome extension or both?:
ion or both?:

**Comment by chinchang** [comment]
Hi @atubo-1 Can you please let me know how I can reproduce this issue?

**Comment by chinchang** [comment]
Should we fixed now. Please confirm.
