### ISSUE TITLE
Error: "No such creation found!" after reloading page

### ISSUE THREAD

**Issue by nhogle** [chinchang/web-maker#557]
## Meta info

- Is this a bug or suggestion?: Bug
- Version (click on help icon in footer): 6.1.0
- Context - Web app, Chrome extension or both?: Web app

As a non-signed in user with many Items saved to LocalStorage, when I open an item, the URL changes to:
`https://webmaker.app/create/item-<item-id>`.  The item loads just fine, but if I refresh the page, then I get an Error alert: "No such creation found!".

**Comment by chinchang** [comment]
Fixed now ✅
