### ISSUE TITLE
localStorage is no longer accessible to my Library items

### ISSUE THREAD

**Issue by nhogle** [chinchang/web-maker#558]
## Meta info

- Is this a bug or suggestion?: Bug
- Version (click on help icon in footer): 6.1.0
- Context - Web app, Chrome extension or both?: Web App

I have many "pens" (Library items) that make use of localStorage to store and persist data between runs.  After the latest updates, I get errors when running my items that use localStorage:
`"Error: Failed to read the 'localStorage' property from 'Window': The document is sandboxed and lacks the 'allow-same-origin' flag.`  

Perhaps this a CORS issue?

Minimal working example: In the JS pane, put: 
```javascript
console.log("localStorage keys:", Object.keys(localStorage));
```

**Comment by chinchang** [comment]
Fixed now ✅
Really appreciate you reporting all the issues, Nick! 🙇🏼‍♂️

**Comment by nhogle** [comment]
@chinchang : I'm so impressed by your responsiveness! Thanks for the quick turn-around on fixing these bugs, it's very much appreciated! :) I'll keep the bug reports coming.  Cheers!

**Comment by chinchang** [comment]
If not much to ask, please do leave a review here -> https://chromewebstore.google.com/detail/web-maker/lkfkkhfhhdkiemehlpkgjeojomhpccnh/reviews 😁
Thanks!
