### ISSUE TITLE
Background blur still used when Fast/light version is enabled

### ISSUE THREAD

**Issue by nhogle** [chinchang/web-maker#559]
## Meta info

- Is this a bug or suggestion?: Bug
- Version (click on help icon in footer): 6.1.0
- Context - Web app, Chrome extension or both?: Web app

If I have the `Fast/light version` switch enabled, I still see background blur on the main UI when modal windows are open.

If I disable `Fast/light version`, it appears that there is even more blur, i.e. double-blur, / blur on top of blur.

**Comment by chinchang** [comment]
Fixed now ✅
