### ISSUE TITLE
Add a javascript console panel (JSbin like)

### ISSUE THREAD

**Issue by paulbonneau** [chinchang/web-maker#56]
features required:

- show `console.*` call outputs. Eg. `console.log`, `console.info` etc.
- show error from preview frame
- evaluate expressions inside the preview frame context
- clear console option
- collapse console option

**Comment by pleabargain** [comment]
+1!

**Comment by satlxq** [comment]
+1

**Comment by GianfrancoFrau** [comment]
+1!

**Comment by chinchang** [comment]
Coming up in 2.6 people 😄

**Comment by chinchang** [comment]
Good news! Console has landed in 2.6.0! Enjoy people 😃
