### ISSUE TITLE
Creations and import of creations unavailable after update to version 6.x

### ISSUE THREAD

**Issue by alexnlong** [chinchang/web-maker#566]
## Meta info

- Is this a bug or suggestion?: Bug
- Version (click on help icon in footer): 6.3.4
- Context - Web app, Chrome extension or both?: Web app

I fortunately exported my code prior to using the latest version of the web app, but now I am unable to access my past creations at all, nor can I import them from a backup. When I attempt to import I see "i18n is not defined" in the devtools console. I was able to replicate this in Firefox (uBlock disabled) and MS Edge (no blockers installed).

**Comment by chinchang** [comment]
Hi @alexnlong you said you are not able to access your past creations. Do you see any error in devtools console when you click "Open"

**Comment by alexnlong** [comment]
I don't get an error after clicking "Open", no warnings either. I might have messed up by signing into Github and then loading the app from a different computer. On the second computer the app's creation list was empty. When I returned to the first computer, the list is now also empty.

Luckily (or so I thought) I had the mind to export the creations before doing the above. However I am not able to import the backup JSON.

**Comment by chinchang** [comment]
Hi @alexnlong! That error message really helped fix the import issue. You should be able to import creations now, whether logged in or not.
Regarding creations not being available, I think you might have logged in to another account through a different social account and that is why you see no creations. Can you please log in again to the account which should have all the saved creations, and in the console run: `window.user.uid`. This will give you your `uid`. Please mail that to me on chinchang457@gmail.com

Really sorry for the inconvenience caused here.

**Comment by alexnlong** [comment]
@chinchang Thank you, that was it. When I logged into the app via my Github account, the creations list was empty, but when I logged out the creations were there again. So now I'm back to trying to import them into the app while logged in. I'm still running into an issue where I get an error while trying to import at this screen:

![Screenshot 2024-06-22 122554](https://github.com/chinchang/web-maker/assets/1895634/033a9d87-c4be-44cc-b4aa-ed59f6b2d100)

```
Uncaught (in promise) FirebaseError: Missing or insufficient permissions.
```

**Comment by chinchang** [comment]
I think I have some idea what might be happening.
@alexnlong Would it be possible to join the Web Maker discord here -> https://discord.gg/v4APKsqmXP
Will be faster to-n-fro to fix this issue.

**Comment by chinchang** [comment]
Hi @alexnlong 
I have released a fix for the reported issue. Now when you try to import some creations which might be already imported in another account, they will still save to your new account.
Please do try and let me know how it goes.
