### ISSUE TITLE
Redirect from old pathname

### ISSUE THREAD

**Issue by sekedus** [chinchang/web-maker#571]
Please automatically redirect when visiting the [`/app/`](https://webmaker.app/app/) page to `/create/`

![screenshot-webmaker app-2024 08 04-07_28_18](https://github.com/user-attachments/assets/fd9eb1cc-9700-49e5-8b37-9e2e31d9a66e)

**Comment by chinchang** [comment]
Hi! How did you reach the `/auto` page?

**Comment by sekedus** [comment]
Oh, sorry...

What I meant was /app/, edited.

**Comment by chinchang** [comment]
Added the redirect! Thanks for suggesting @sekedus 🙇🏼‍♂️
