### ISSUE TITLE
App crashes on initial load when loading creation with Stylus CSS mode

### ISSUE THREAD

**Issue by nhogle** [chinchang/web-maker#575]
## Meta info

- Is this a bug or suggestion?: Bug
- Version (click on help icon in footer): 6.4.0
- Context - Web app, Chrome extension or both?: Web app

App crashes at [this line](https://github.com/chinchang/web-maker/blob/decc221b835686463f8298715d968e4a6e37ff88/src/computes.js#L105), when trying to apply stylus transformation to the CSS code.  This causes cascading failures:
  * None of the buttons work (Assets, Add Library, New, Login/Signup). 
  * Clicking "Open" blurs out the screen, then the Library panel does _not_ appear, and then nothing else can be done.

It looks like this is a race condition, wherein the app is trying to call into the Stylus library before it has had a chance to load.  The [`handleModeRequirements()` function](https://github.com/chinchang/web-maker/blob/decc221b835686463f8298715d968e4a6e37ff88/src/utils.js#L609C17-L609C39) is supposed to load the stylus .js file, but somehow this is not completing before we get to `compute.js#L105`.  

Steps to reproduce:
1.  Create a blank creation, with modes: HTML / Stylus / JS
2. Publish the creation to a public url
3. Open that url in a new incognito window.
4. App crashes when trying to apply stylus transformation.

**Comment by nhogle** [comment]
I have also seen this bug happen without using incognito windows, it's just trickier to reproduce it.  Perhaps the app is loading the Stylus .js from cache before the race condition occurs?  I would need to do more testing to reproduce...

**Comment by chinchang** [comment]
seems to be working for me, all the time.
I also checked the code for possible race conditions - stylus.js is always ensured to be loaded before actually using it in compute function. So I am not sure how could a race condition happen here.
@nhogle Actual error from the console might help here. What error(s) are you getting there?

**Comment by nhogle** [comment]
```
y (bundle.bb774.js?_sw-precache=7f80aa03be5078c473913b806ee7bcc5:84)
setPreviewContent (bundle.bb774.js?_sw-precache=7f80aa03be5078c473913b806ee7bcc5:84)
(anonymous) (bundle.bb774.js?_sw-precache=7f80aa03be5078c473913b806ee7bcc5:84)
(anonymous) (bundle.bb774.js?_sw-precache=7f80aa03be5078c473913b806ee7bcc5:84)
(anonymous) (bundle.bb774.js?_sw-precache=7f80aa03be5078c473913b806ee7bcc5:84)
k (bundle.bb774.js?_sw-precache=7f80aa03be5078c473913b806ee7bcc5:84)
p (bundle.bb774.js?_sw-precache=7f80aa03be5078c473913b806ee7bcc5:84)
Promise.then
d (bundle.bb774.js?_sw-precache=7f80aa03be5078c473913b806ee7bcc5:84)
c.setState (bundle.bb774.js?_sw-precache=7f80aa03be5078c473913b806ee7bcc5:84)
toggleLayout (bundle.bb774.js?_sw-precache=7f80aa03be5078c473913b806ee7bcc5:84)
refreshEditor (bundle.bb774.js?_sw-precache=7f80aa03be5078c473913b806ee7bcc5:84)
(anonymous) (bundle.bb774.js?_sw-precache=7f80aa03be5078c473913b806ee7bcc5:84)
Promise.then
(anonymous) (bundle.bb774.js?_sw-precache=7f80aa03be5078c473913b806ee7bcc5:84)
Promise.then
(anonymous) (bundle.bb774.js?_sw-precache=7f80aa03be5078c473913b806ee7bcc5:84)
Promise.then
componentWillMount (bundle.bb774.js?_sw-precache=7f80aa03be5078c473913b806ee7bcc5:84)
C (bundle.bb774.js?_sw-precache=7f80aa03be5078c473913b806ee7bcc5:84)
f (bundle.bb774.js?_sw-precache=7f80aa03be5078c473913b806ee7bcc5:84)
C (bundle.bb774.js?_sw-precache=7f80aa03be5078c473913b806ee7bcc5:84)
f (bundle.bb774.js?_sw-precache=7f80aa03be5078c473913b806ee7bcc5:84)
C (bundle.bb774.js?_sw-precache=7f80aa03be5078c473913b806ee7bcc5:84)
f (bundle.bb774.js?_sw-precache=7f80aa03be5078c473913b806ee7bcc5:84)
C (bundle.bb774.js?_sw-precache=7f80aa03be5078c473913b806ee7bcc5:84)
A (bundle.bb774.js?_sw-precache=7f80aa03be5078c473913b806ee7bcc5:84)
i (bundle.bb774.js?_sw-precache=7f80aa03be5078c473913b806ee7bcc5:84)
(anonymous) (bundle.bb774.js?_sw-precache=7f80aa03be5078c473913b806ee7bcc5:84)
(anonymous) (bundle.bb774.js?_sw-precache=7f80aa03be5078c473913b806ee7bcc5:84)
(anonymous) (bundle.bb774.js?_sw-precache=7f80aa03be5078c473913b806ee7bcc5:84)
```

Error: 
```
bundle.bb774.js?_sw-precache=7f80aa03be5078c473913b806ee7bcc5:84 Uncaught (in promise) ReferenceError: stylus is not defined
    at y (bundle.bb774.js?_sw-precache=7f80aa03be5078c473913b806ee7bcc5:84:568710)
    at u_.setPreviewContent (bundle.bb774.js?_sw-precache=7f80aa03be5078c473913b806ee7bcc5:84:985271)
    at QF.<anonymous> (bundle.bb774.js?_sw-precache=7f80aa03be5078c473913b806ee7bcc5:84:1424488)
    at bundle.bb774.js?_sw-precache=7f80aa03be5078c473913b806ee7bcc5:84:554665
    at Array.some (<anonymous>)
    at bundle.bb774.js?_sw-precache=7f80aa03be5078c473913b806ee7bcc5:84:554645
    at Array.some (<anonymous>)
    at k (bundle.bb774.js?_sw-precache=7f80aa03be5078c473913b806ee7bcc5:84:554604)
    at p (bundle.bb774.js?_sw-precache=7f80aa03be5078c473913b806ee7bcc5:84:549044)
y @ bundle.bb774.js?_sw-precache=7f80aa03be5078c473913b806ee7bcc5:84
setPreviewContent @ bundle.bb774.js?_sw-precache=7f80aa03be5078c473913b806ee7bcc5:84
(anonymous) @ bundle.bb774.js?_sw-precache=7f80aa03be5078c473913b806ee7bcc5:84
(anonymous) @ bundle.bb774.js?_sw-precache=7f80aa03be5078c473913b806ee7bcc5:84
(anonymous) @ bundle.bb774.js?_sw-precache=7f80aa03be5078c473913b806ee7bcc5:84
k @ bundle.bb774.js?_sw-precache=7f80aa03be5078c473913b806ee7bcc5:84
p @ bundle.bb774.js?_sw-precache=7f80aa03be5078c473913b806ee7bcc5:84
Promise.then
d @ bundle.bb774.js?_sw-precache=7f80aa03be5078c473913b806ee7bcc5:84
c.setState @ bundle.bb774.js?_sw-precache=7f80aa03be5078c473913b806ee7bcc5:84
toggleLayout @ bundle.bb774.js?_sw-precache=7f80aa03be5078c473913b806ee7bcc5:84
refreshEditor @ bundle.bb774.js?_sw-precache=7f80aa03be5078c473913b806ee7bcc5:84
(anonymous) @ bundle.bb774.js?_sw-precache=7f80aa03be5078c473913b806ee7bcc5:84
Promise.then
(anonymous) @ bundle.bb774.js?_sw-precache=7f80aa03be5078c473913b806ee7bcc5:84
Promise.then
(anonymous) @ bundle.bb774.js?_sw-precache=7f80aa03be5078c473913b806ee7bcc5:84
Promise.then
componentWillMount @ bundle.bb774.js?_sw-precache=7f80aa03be5078c473913b806ee7bcc5:84
C @ bundle.bb774.js?_sw-precache=7f80aa03be5078c473913b806ee7bcc5:84
f @ bundle.bb774.js?_sw-precache=7f80aa03be5078c473913b806ee7bcc5:84
C @ bundle.bb774.js?_sw-precache=7f80aa03be5078c473913b806ee7bcc5:84
f @ bundle.bb774.js?_sw-precache=7f80aa03be5078c473913b806ee7bcc5:84
C @ bundle.bb774.js?_sw-precache=7f80aa03be5078c473913b806ee7bcc5:84
f @ bundle.bb774.js?_sw-precache=7f80aa03be5078c473913b806ee7bcc5:84
C @ bundle.bb774.js?_sw-precache=7f80aa03be5078c473913b806ee7bcc5:84
A @ bundle.bb774.js?_sw-precache=7f80aa03be5078c473913b806ee7bcc5:84
i @ bundle.bb774.js?_sw-precache=7f80aa03be5078c473913b806ee7bcc5:84
(anonymous) @ bundle.bb774.js?_sw-precache=7f80aa03be5078c473913b806ee7bcc5:84
(anonymous) @ bundle.bb774.js?_sw-precache=7f80aa03be5078c473913b806ee7bcc5:84
(anonymous) @ bundle.bb774.js?_sw-precache=7f80aa03be5078c473913b806ee7bcc5:84
```

**Comment by nhogle** [comment]
sorry the stack trace is difficult to look at.. I was cross-referencing it with the original source. Would it be possible to publish a source map on the production site? That might help. But at least with this stack trace, do you think you can spot the issue? 

Cheers,
-Nick

**Comment by nhogle** [comment]
Okay, I've dissected the stack trace, and I think I've narrowed it down.  The problem, perhaps, is that `app#toggleLayout()` calls `ContentWrap#setPreviewContent()` directly [here](https://github.com/chinchang/web-maker/blob/decc221b835686463f8298715d968e4a6e37ff88/src/components/app.jsx#L829), bypassing the Javscript preloading that happens [here](https://github.com/chinchang/web-maker/blob/decc221b835686463f8298715d968e4a6e37ff88/src/components/ContentWrap.jsx#L329).  Perhaps `app#toggleLayout()` line `829` should instead read:
```javascript
this.contentWrap.refreshEditor();
``` 

Note that the call to `app#toggleLayout()` happens on component mount when [trying to look up the layout mode](https://github.com/chinchang/web-maker/blob/decc221b835686463f8298715d968e4a6e37ff88/src/components/app.jsx#L284) from index db.  On a fresh load of the app, when the app's `state.currentLayoutMode` is `undefined`, then `toggleLayout()`'s logic will fall through to line `829`.

**Comment by chinchang** [comment]
Ah I see now. Thanks for debugging this case Nick!
I am on it right now.

**Comment by chinchang** [comment]
@nhogle Released a fix. Let me know how it works for you.

**Comment by nhogle** [comment]
@chinchang : Yes! It is now working as expected.  Thank you Kushagra!
