### ISSUE TITLE
new item file name uses wrong date

### ISSUE THREAD

**Issue by pleabargain** [chinchang/web-maker#58]
I create a new item
file name shows
**Untitled 29-0-12:53**
but today is 29 JAN || 29-1 but !29-0

desired behavior:
user has choice of date formats e.g.

- 29JAN2017 untitled (MY preference)
- JAN292017untitled
- etc.

here's the video
https://youtu.be/Ak4ykX1rdP8

thank you
Dennis

**Comment by chinchang** [comment]
This has been fixed in v2.3.0. Though option to choose format will come in future.

**Comment by pleabargain** [comment]
Great! Thanks.
