### ISSUE TITLE
put version number in settings... make the user version easy to ID

### ISSUE THREAD

**Issue by pleabargain** [chinchang/web-maker#69]
![image](https://cloud.githubusercontent.com/assets/640846/22687513/6c033006-ed39-11e6-93b1-949d6ce0ad54.png)

**Comment by chinchang** [comment]
Sure. Will put there. BTW, it shows in the help/about box:
![screenshot 2017 02 08 01 27 21](https://cloud.githubusercontent.com/assets/379918/22708896/f6c27b70-ed9d-11e6-93d0-76afc94ad816.png)

**Comment by pleabargain** [comment]
:) Thank you! I didn't know that!

**Comment by chinchang** [comment]
Live in 2.3.2
