### ISSUE TITLE
Can’t do @import compass/css3

### ISSUE THREAD

**Issue by jkantner** [chinchang/web-maker#70]
I tried to use trig functions like sin() and cos(), so I did `@import compass/css3` and got this error as a result:

> File to import not found or unreadable: compass/CSS3 Parent style sheet: stdin

Is importing Sass libraries supported, or is there a Web Maker-specific way to import Sass libraries?

**Comment by chinchang** [comment]
Importing libraries isn't supported right now in Sass. Let me check this.

**Comment by yumyo** [comment]
+1
