### ISSUE TITLE
when saving to local drive use the existing name of the file

### ISSUE THREAD

**Issue by pleabargain** [chinchang/web-maker#71]
my doc has a name
![image](https://cloud.githubusercontent.com/assets/640846/22852736/eda907a8-f053-11e6-8456-5eaf7fb7ae46.png)
but
when i go to save as html the name I gave the file is overwritten
![image](https://cloud.githubusercontent.com/assets/640846/22852746/0ffbcfb6-f054-11e6-9f12-4100f3b41622.png)

On file save as, get the name of the file that the user gave it.

example.
user saves local file as mydoc
on save to html
mydoc.html 
is the name.

thank you
Dennis

**Comment by chinchang** [comment]
fixed in 2.3.1
