### ISSUE TITLE
Firefox or Electron support

### ISSUE THREAD

**Issue by mitchellknight** [chinchang/web-maker#77]
I don't use Chrome. Are you planning a Firefox version? If not, what about an Electron version?

**Comment by chinchang** [comment]
Porting to FIrefox would be technically difficult considering difference in how Chrome and FIrefox extensions work. But electron version seems completely doable. Will test this and update here on progress.

**Comment by BasitAli** [comment]
I tried giving it a go but the project relies too much on the chrome apis that are unavailable in electron. The interface launches up great but the rest of the stuff doesn't work. I'm still interested in working on it but need to see how much time I can spend on it.

**Comment by BasitAli** [comment]
Update: Having some success with NW.js. Other than console logs, editing and previewing seems to be working.

![image](https://user-images.githubusercontent.com/869390/29185804-e087d0f0-7e23-11e7-9da2-8b565d44fa60.png)

**Comment by BasitAli** [comment]
I've updated my fork at https://github.com/BasitAli/web-maker with support for standalone package based on NW.js. `build.js` is the script that generates the build and, for now, only packages for osx64. Running `npm run build` will package and place the .app file in the `build` folder.

**Comment by chinchang** [comment]
Hey @BasitAli, this looks really amazing! Thanks for your contribution 🙇 . I'll check out your fork and put in my comments here.
I am also planning to wrap all Chrome API code/features inside a flag which can be simply turned on & off on various platforms - that will make porting easier.

**Comment by marsjaninzmarsa** [comment]
@chinchang:
> Porting to FIrefox would be technically difficult considering difference in how Chrome and FIrefox extensions work.

[Are they really so huge](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Chrome_incompatibilities)? :wink:

**Comment by chinchang** [comment]
Tried running on Firefox. Documenting the issues here:
- `requestFileSystem` API required to create script & preview html file is missing in Firefox. The [alternative API](https://developer.mozilla.org/en-US/docs/Web/API/File_and_Directory_Entries_API/Firefox_support) doesn't supports file writing!
- `downloads` is an invalid optional permission in Firefox.

**Comment by chinchang** [comment]
**UPDATE**

Good news! I made Web Maker work in Firefox :D The approach I am using seems to be working on all tests until now. Though it won't be an extension. It would be a web app but it will work completely offline! So the most important feature stays :)
Hoping to release a beta soon in the coming week.

**Comment by chinchang** [comment]
Hey everyone! Now you can use Web Maker in Firefox too - with the all new **Web Maker** web app! 🔥 https://webmakerapp.com/app/
Its usable on Safari by turning off the cross origin restriction. Will soon fix that too. 
Enjoy :)
