### ISSUE TITLE
Change the key short for ctrl+s

### ISSUE THREAD

**Issue by MKFMIKU** [chinchang/web-maker#8]
When I press the ctrl-s, I usually means save the html which I'm working on.But file saved that is the web Maker's html.

I think it could prevent the key short and the save the file that woking on

```
 if ((event.ctrlKey)&&(event.keyCode==83))   
     event.returnValue=false;
```

**Comment by chinchang** [comment]
fixed in v1.6.0

Thanks @MKFMIKU :)
