### ISSUE TITLE
SCSS/Sass bug: Using transform `skewY(90deg)` causes Web Maker to freeze

### ISSUE THREAD

**Issue by jkantner** [chinchang/web-maker#87]
I was playing around with this SCSS style in a project and changed `skewY(-30deg)` to 90, and then the app froze:
```
transform: rotateX(0deg) rotateZ(60deg) skewX(0deg) skewY(-30deg) {
    origin: 0 0;
};
```

**Comment by chinchang** [comment]
Hi @jkantner 

I suppose the code you have mentioned is syntactically wrong. You have mentioned `origin` as a property instead of `transform-origin`. Am I right?

**Comment by jkantner** [comment]
In SCSS, this syntax is legal. In closures like these, you can use any property beginning with `property-` without including that part as long as `property-subproperty` is a real property in normal CSS.

In other words, you can set a background with a color, image, and position without repeating `background-` before those properties as long as they are inside `background {}`.
```
element {
    background: {
        color: blue;
        image: radial-gradient(#fff 50%, transparent 50%);
        position: -50px 0;
    };
}
```
