### ISSUE TITLE
Detached preview window

### ISSUE THREAD

**Issue by chinchang** [chinchang/web-maker#92]
If preview can be detached into a separate window, multiple monitors can be used for a better experience with editing happening on one monitor and live preview on other.

https://twitter.com/derekbtw/status/841027257984417792

**Comment by derekbtw** [comment]
I'm really excited for this to become a thing. I'll fork the repo and help out 👍

**Comment by chinchang** [comment]
@derekbtw Looking forward. I am excited about this too!

**Comment by chinchang** [comment]
This is live in 2.9. Thanks for suggesting @derekbtw 👍

**Comment by derekbtw** [comment]
Sweet! Thanks for the implementation!
