### ISSUE TITLE
Resize forces refresh/reload of the page

### ISSUE THREAD

**Issue by krulik** [chinchang/web-maker#97]
Steps:
- Resize the preview pane

Expected:
- Preview will be new size without additional side effects

Actual:
- Preview pane is being reloaded.

This bug makes it hard to maintain context while working on a responsive website/component.

**Comment by chinchang** [comment]
@krulik This was intentionally added because a refresh might be required in case of a JavaScript depending on window width/height. But I agree, your use case is also completely valid. So I guess I'll add it as a configurable setting.

**Comment by krulik** [comment]
@chinchang 👍  sounds great

**Comment by chinchang** [comment]
This is live in 2.5.0
